version: "3.1"

services:
  db:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysecretpass
