/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// EmbeddedServiceModel struct for EmbeddedServiceModel
type EmbeddedServiceModel struct {
	// The service id
	Id string `json:"id"`
	// The code for the service
	Code *string `json:"code,omitempty"`
	// The name for the service
	Name *string `json:"name,omitempty"`
	// The description for the service
	Description *string `json:"description,omitempty"`
}

// NewEmbeddedServiceModel instantiates a new EmbeddedServiceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedServiceModel(id string) *EmbeddedServiceModel {
	this := EmbeddedServiceModel{}
	this.Id = id
	return &this
}

// NewEmbeddedServiceModelWithDefaults instantiates a new EmbeddedServiceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedServiceModelWithDefaults() *EmbeddedServiceModel {
	this := EmbeddedServiceModel{}
	return &this
}

// GetId returns the Id field value
func (o *EmbeddedServiceModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmbeddedServiceModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmbeddedServiceModel) SetId(v string) {
	o.Id = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *EmbeddedServiceModel) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedServiceModel) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *EmbeddedServiceModel) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *EmbeddedServiceModel) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmbeddedServiceModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedServiceModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmbeddedServiceModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmbeddedServiceModel) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EmbeddedServiceModel) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedServiceModel) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EmbeddedServiceModel) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EmbeddedServiceModel) SetDescription(v string) {
	o.Description = &v
}

func (o EmbeddedServiceModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedServiceModel struct {
	value *EmbeddedServiceModel
	isSet bool
}

func (v NullableEmbeddedServiceModel) Get() *EmbeddedServiceModel {
	return v.value
}

func (v *NullableEmbeddedServiceModel) Set(val *EmbeddedServiceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedServiceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedServiceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedServiceModel(val *EmbeddedServiceModel) *NullableEmbeddedServiceModel {
	return &NullableEmbeddedServiceModel{value: val, isSet: true}
}

func (v NullableEmbeddedServiceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedServiceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


