/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// ReservationServiceListModel struct for ReservationServiceListModel
type ReservationServiceListModel struct {
	// The list of services booked for the reservation
	Services []ReservationServiceItemModel `json:"services"`
	// Total count of items
	Count int64 `json:"count"`
}

// NewReservationServiceListModel instantiates a new ReservationServiceListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationServiceListModel(services []ReservationServiceItemModel, count int64) *ReservationServiceListModel {
	this := ReservationServiceListModel{}
	this.Services = services
	this.Count = count
	return &this
}

// NewReservationServiceListModelWithDefaults instantiates a new ReservationServiceListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationServiceListModelWithDefaults() *ReservationServiceListModel {
	this := ReservationServiceListModel{}
	return &this
}

// GetServices returns the Services field value
func (o *ReservationServiceListModel) GetServices() []ReservationServiceItemModel {
	if o == nil {
		var ret []ReservationServiceItemModel
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *ReservationServiceListModel) GetServicesOk() (*[]ReservationServiceItemModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *ReservationServiceListModel) SetServices(v []ReservationServiceItemModel) {
	o.Services = v
}

// GetCount returns the Count field value
func (o *ReservationServiceListModel) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ReservationServiceListModel) GetCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ReservationServiceListModel) SetCount(v int64) {
	o.Count = v
}

func (o ReservationServiceListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["services"] = o.Services
	}
	if true {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableReservationServiceListModel struct {
	value *ReservationServiceListModel
	isSet bool
}

func (v NullableReservationServiceListModel) Get() *ReservationServiceListModel {
	return v.value
}

func (v *NullableReservationServiceListModel) Set(val *ReservationServiceListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationServiceListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationServiceListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationServiceListModel(val *ReservationServiceListModel) *NullableReservationServiceListModel {
	return &NullableReservationServiceListModel{value: val, isSet: true}
}

func (v NullableReservationServiceListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationServiceListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


