/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// ReservationValidationMessageModel struct for ReservationValidationMessageModel
type ReservationValidationMessageModel struct {
	// The message category
	Category string `json:"category"`
	// The message Code
	Code string `json:"code"`
	// The message description
	Message string `json:"message"`
}

// NewReservationValidationMessageModel instantiates a new ReservationValidationMessageModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationValidationMessageModel(category string, code string, message string) *ReservationValidationMessageModel {
	this := ReservationValidationMessageModel{}
	this.Category = category
	this.Code = code
	this.Message = message
	return &this
}

// NewReservationValidationMessageModelWithDefaults instantiates a new ReservationValidationMessageModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationValidationMessageModelWithDefaults() *ReservationValidationMessageModel {
	this := ReservationValidationMessageModel{}
	return &this
}

// GetCategory returns the Category field value
func (o *ReservationValidationMessageModel) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ReservationValidationMessageModel) GetCategoryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ReservationValidationMessageModel) SetCategory(v string) {
	o.Category = v
}

// GetCode returns the Code field value
func (o *ReservationValidationMessageModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ReservationValidationMessageModel) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ReservationValidationMessageModel) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *ReservationValidationMessageModel) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ReservationValidationMessageModel) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ReservationValidationMessageModel) SetMessage(v string) {
	o.Message = v
}

func (o ReservationValidationMessageModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["category"] = o.Category
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableReservationValidationMessageModel struct {
	value *ReservationValidationMessageModel
	isSet bool
}

func (v NullableReservationValidationMessageModel) Get() *ReservationValidationMessageModel {
	return v.value
}

func (v *NullableReservationValidationMessageModel) Set(val *ReservationValidationMessageModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationValidationMessageModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationValidationMessageModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationValidationMessageModel(val *ReservationValidationMessageModel) *NullableReservationValidationMessageModel {
	return &NullableReservationValidationMessageModel{value: val, isSet: true}
}

func (v NullableReservationValidationMessageModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationValidationMessageModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


