/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// BookingListModel struct for BookingListModel
type BookingListModel struct {
	Bookings []BookingItemModel `json:"bookings"`
	// Total count of items
	Count int64 `json:"count"`
}

// NewBookingListModel instantiates a new BookingListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookingListModel(bookings []BookingItemModel, count int64) *BookingListModel {
	this := BookingListModel{}
	this.Bookings = bookings
	this.Count = count
	return &this
}

// NewBookingListModelWithDefaults instantiates a new BookingListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookingListModelWithDefaults() *BookingListModel {
	this := BookingListModel{}
	return &this
}

// GetBookings returns the Bookings field value
func (o *BookingListModel) GetBookings() []BookingItemModel {
	if o == nil {
		var ret []BookingItemModel
		return ret
	}

	return o.Bookings
}

// GetBookingsOk returns a tuple with the Bookings field value
// and a boolean to check if the value has been set.
func (o *BookingListModel) GetBookingsOk() (*[]BookingItemModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Bookings, true
}

// SetBookings sets field value
func (o *BookingListModel) SetBookings(v []BookingItemModel) {
	o.Bookings = v
}

// GetCount returns the Count field value
func (o *BookingListModel) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *BookingListModel) GetCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *BookingListModel) SetCount(v int64) {
	o.Count = v
}

func (o BookingListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bookings"] = o.Bookings
	}
	if true {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableBookingListModel struct {
	value *BookingListModel
	isSet bool
}

func (v NullableBookingListModel) Get() *BookingListModel {
	return v.value
}

func (v *NullableBookingListModel) Set(val *BookingListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBookingListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBookingListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookingListModel(val *BookingListModel) *NullableBookingListModel {
	return &NullableBookingListModel{value: val, isSet: true}
}

func (v NullableBookingListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookingListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


