/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// BookingCreatedModel struct for BookingCreatedModel
type BookingCreatedModel struct {
	// Booking id
	Id string `json:"id"`
	// List of ids for newly created reservations
	ReservationIds []ReservationCreatedModel `json:"reservationIds"`
}

// NewBookingCreatedModel instantiates a new BookingCreatedModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookingCreatedModel(id string, reservationIds []ReservationCreatedModel) *BookingCreatedModel {
	this := BookingCreatedModel{}
	this.Id = id
	this.ReservationIds = reservationIds
	return &this
}

// NewBookingCreatedModelWithDefaults instantiates a new BookingCreatedModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookingCreatedModelWithDefaults() *BookingCreatedModel {
	this := BookingCreatedModel{}
	return &this
}

// GetId returns the Id field value
func (o *BookingCreatedModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BookingCreatedModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BookingCreatedModel) SetId(v string) {
	o.Id = v
}

// GetReservationIds returns the ReservationIds field value
func (o *BookingCreatedModel) GetReservationIds() []ReservationCreatedModel {
	if o == nil {
		var ret []ReservationCreatedModel
		return ret
	}

	return o.ReservationIds
}

// GetReservationIdsOk returns a tuple with the ReservationIds field value
// and a boolean to check if the value has been set.
func (o *BookingCreatedModel) GetReservationIdsOk() (*[]ReservationCreatedModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReservationIds, true
}

// SetReservationIds sets field value
func (o *BookingCreatedModel) SetReservationIds(v []ReservationCreatedModel) {
	o.ReservationIds = v
}

func (o BookingCreatedModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["reservationIds"] = o.ReservationIds
	}
	return json.Marshal(toSerialize)
}

type NullableBookingCreatedModel struct {
	value *BookingCreatedModel
	isSet bool
}

func (v NullableBookingCreatedModel) Get() *BookingCreatedModel {
	return v.value
}

func (v *NullableBookingCreatedModel) Set(val *BookingCreatedModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBookingCreatedModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBookingCreatedModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookingCreatedModel(val *BookingCreatedModel) *NullableBookingCreatedModel {
	return &NullableBookingCreatedModel{value: val, isSet: true}
}

func (v NullableBookingCreatedModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookingCreatedModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


