/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// AmountModel struct for AmountModel
type AmountModel struct {
	GrossAmount float64 `json:"grossAmount"`
	NetAmount float64 `json:"netAmount"`
	VatType string `json:"vatType"`
	VatPercent float64 `json:"vatPercent"`
	Currency string `json:"currency"`
}

// NewAmountModel instantiates a new AmountModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmountModel(grossAmount float64, netAmount float64, vatType string, vatPercent float64, currency string) *AmountModel {
	this := AmountModel{}
	this.GrossAmount = grossAmount
	this.NetAmount = netAmount
	this.VatType = vatType
	this.VatPercent = vatPercent
	this.Currency = currency
	return &this
}

// NewAmountModelWithDefaults instantiates a new AmountModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmountModelWithDefaults() *AmountModel {
	this := AmountModel{}
	return &this
}

// GetGrossAmount returns the GrossAmount field value
func (o *AmountModel) GetGrossAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.GrossAmount
}

// GetGrossAmountOk returns a tuple with the GrossAmount field value
// and a boolean to check if the value has been set.
func (o *AmountModel) GetGrossAmountOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GrossAmount, true
}

// SetGrossAmount sets field value
func (o *AmountModel) SetGrossAmount(v float64) {
	o.GrossAmount = v
}

// GetNetAmount returns the NetAmount field value
func (o *AmountModel) GetNetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.NetAmount
}

// GetNetAmountOk returns a tuple with the NetAmount field value
// and a boolean to check if the value has been set.
func (o *AmountModel) GetNetAmountOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetAmount, true
}

// SetNetAmount sets field value
func (o *AmountModel) SetNetAmount(v float64) {
	o.NetAmount = v
}

// GetVatType returns the VatType field value
func (o *AmountModel) GetVatType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VatType
}

// GetVatTypeOk returns a tuple with the VatType field value
// and a boolean to check if the value has been set.
func (o *AmountModel) GetVatTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.VatType, true
}

// SetVatType sets field value
func (o *AmountModel) SetVatType(v string) {
	o.VatType = v
}

// GetVatPercent returns the VatPercent field value
func (o *AmountModel) GetVatPercent() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.VatPercent
}

// GetVatPercentOk returns a tuple with the VatPercent field value
// and a boolean to check if the value has been set.
func (o *AmountModel) GetVatPercentOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.VatPercent, true
}

// SetVatPercent sets field value
func (o *AmountModel) SetVatPercent(v float64) {
	o.VatPercent = v
}

// GetCurrency returns the Currency field value
func (o *AmountModel) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *AmountModel) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *AmountModel) SetCurrency(v string) {
	o.Currency = v
}

func (o AmountModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["grossAmount"] = o.GrossAmount
	}
	if true {
		toSerialize["netAmount"] = o.NetAmount
	}
	if true {
		toSerialize["vatType"] = o.VatType
	}
	if true {
		toSerialize["vatPercent"] = o.VatPercent
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullableAmountModel struct {
	value *AmountModel
	isSet bool
}

func (v NullableAmountModel) Get() *AmountModel {
	return v.value
}

func (v *NullableAmountModel) Set(val *AmountModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAmountModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAmountModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmountModel(val *AmountModel) *NullableAmountModel {
	return &NullableAmountModel{value: val, isSet: true}
}

func (v NullableAmountModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmountModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


