/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// ReservationAssignedUnitModel struct for ReservationAssignedUnitModel
type ReservationAssignedUnitModel struct {
	Unit EmbeddedUnitModel `json:"unit"`
	// The time ranges for which the unit is assigned to the reservation
	TimeRanges []ReservationAssignedUnitTimeRangeModel `json:"timeRanges"`
}

// NewReservationAssignedUnitModel instantiates a new ReservationAssignedUnitModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationAssignedUnitModel(unit EmbeddedUnitModel, timeRanges []ReservationAssignedUnitTimeRangeModel) *ReservationAssignedUnitModel {
	this := ReservationAssignedUnitModel{}
	this.Unit = unit
	this.TimeRanges = timeRanges
	return &this
}

// NewReservationAssignedUnitModelWithDefaults instantiates a new ReservationAssignedUnitModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationAssignedUnitModelWithDefaults() *ReservationAssignedUnitModel {
	this := ReservationAssignedUnitModel{}
	return &this
}

// GetUnit returns the Unit field value
func (o *ReservationAssignedUnitModel) GetUnit() EmbeddedUnitModel {
	if o == nil {
		var ret EmbeddedUnitModel
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *ReservationAssignedUnitModel) GetUnitOk() (*EmbeddedUnitModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *ReservationAssignedUnitModel) SetUnit(v EmbeddedUnitModel) {
	o.Unit = v
}

// GetTimeRanges returns the TimeRanges field value
func (o *ReservationAssignedUnitModel) GetTimeRanges() []ReservationAssignedUnitTimeRangeModel {
	if o == nil {
		var ret []ReservationAssignedUnitTimeRangeModel
		return ret
	}

	return o.TimeRanges
}

// GetTimeRangesOk returns a tuple with the TimeRanges field value
// and a boolean to check if the value has been set.
func (o *ReservationAssignedUnitModel) GetTimeRangesOk() (*[]ReservationAssignedUnitTimeRangeModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TimeRanges, true
}

// SetTimeRanges sets field value
func (o *ReservationAssignedUnitModel) SetTimeRanges(v []ReservationAssignedUnitTimeRangeModel) {
	o.TimeRanges = v
}

func (o ReservationAssignedUnitModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["unit"] = o.Unit
	}
	if true {
		toSerialize["timeRanges"] = o.TimeRanges
	}
	return json.Marshal(toSerialize)
}

type NullableReservationAssignedUnitModel struct {
	value *ReservationAssignedUnitModel
	isSet bool
}

func (v NullableReservationAssignedUnitModel) Get() *ReservationAssignedUnitModel {
	return v.value
}

func (v *NullableReservationAssignedUnitModel) Set(val *ReservationAssignedUnitModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationAssignedUnitModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationAssignedUnitModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationAssignedUnitModel(val *ReservationAssignedUnitModel) *NullableReservationAssignedUnitModel {
	return &NullableReservationAssignedUnitModel{value: val, isSet: true}
}

func (v NullableReservationAssignedUnitModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationAssignedUnitModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


