/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// OfferNoShowFeeModel struct for OfferNoShowFeeModel
type OfferNoShowFeeModel struct {
	// The code of the no-show policy applied
	Code string `json:"code"`
	// The name of the no-show policy applied
	Name string `json:"name"`
	// The description of the no-show policy applied
	Description string `json:"description"`
	Fee MonetaryValueModel `json:"fee"`
}

// NewOfferNoShowFeeModel instantiates a new OfferNoShowFeeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferNoShowFeeModel(code string, name string, description string, fee MonetaryValueModel) *OfferNoShowFeeModel {
	this := OfferNoShowFeeModel{}
	this.Code = code
	this.Name = name
	this.Description = description
	this.Fee = fee
	return &this
}

// NewOfferNoShowFeeModelWithDefaults instantiates a new OfferNoShowFeeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferNoShowFeeModelWithDefaults() *OfferNoShowFeeModel {
	this := OfferNoShowFeeModel{}
	return &this
}

// GetCode returns the Code field value
func (o *OfferNoShowFeeModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *OfferNoShowFeeModel) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *OfferNoShowFeeModel) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *OfferNoShowFeeModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OfferNoShowFeeModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OfferNoShowFeeModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *OfferNoShowFeeModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *OfferNoShowFeeModel) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *OfferNoShowFeeModel) SetDescription(v string) {
	o.Description = v
}

// GetFee returns the Fee field value
func (o *OfferNoShowFeeModel) GetFee() MonetaryValueModel {
	if o == nil {
		var ret MonetaryValueModel
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *OfferNoShowFeeModel) GetFeeOk() (*MonetaryValueModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *OfferNoShowFeeModel) SetFee(v MonetaryValueModel) {
	o.Fee = v
}

func (o OfferNoShowFeeModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["fee"] = o.Fee
	}
	return json.Marshal(toSerialize)
}

type NullableOfferNoShowFeeModel struct {
	value *OfferNoShowFeeModel
	isSet bool
}

func (v NullableOfferNoShowFeeModel) Get() *OfferNoShowFeeModel {
	return v.value
}

func (v *NullableOfferNoShowFeeModel) Set(val *OfferNoShowFeeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferNoShowFeeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferNoShowFeeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferNoShowFeeModel(val *OfferNoShowFeeModel) *NullableOfferNoShowFeeModel {
	return &NullableOfferNoShowFeeModel{value: val, isSet: true}
}

func (v NullableOfferNoShowFeeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferNoShowFeeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


