/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// GuestModel struct for GuestModel
type GuestModel struct {
	// Title of the guest
	Title *string `json:"title,omitempty"`
	// Gender of the booker
	Gender *string `json:"gender,omitempty"`
	// First name of the guest
	FirstName *string `json:"firstName,omitempty"`
	// Middle initial of the guest
	MiddleInitial *string `json:"middleInitial,omitempty"`
	// Last name of the guest
	LastName string `json:"lastName"`
	// Email address of the guest
	Email *string `json:"email,omitempty"`
	// Phone number of the guest
	Phone *string `json:"phone,omitempty"`
	Address *PersonAddressModel `json:"address,omitempty"`
	// The guest's nationality, in ISO 3166-1 alpha-2 code
	NationalityCountryCode *string `json:"nationalityCountryCode,omitempty"`
	// The guest's identification number for the given identificationType.
	IdentificationNumber *string `json:"identificationNumber,omitempty"`
	// The issue date of the guest's identification document.
	IdentificationIssueDate *string `json:"identificationIssueDate,omitempty"`
	// The type of the identificationNumber
	IdentificationType *string `json:"identificationType,omitempty"`
	Company *PersonCompanyModel `json:"company,omitempty"`
	// Two-letter code (ISO Alpha-2) of a language preferred for contact
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
	// Guest's birthdate
	BirthDate *string `json:"birthDate,omitempty"`
	// Guest's place of birth
	BirthPlace *string `json:"birthPlace,omitempty"`
}

// NewGuestModel instantiates a new GuestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuestModel(lastName string) *GuestModel {
	this := GuestModel{}
	this.LastName = lastName
	return &this
}

// NewGuestModelWithDefaults instantiates a new GuestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuestModelWithDefaults() *GuestModel {
	this := GuestModel{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GuestModel) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GuestModel) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GuestModel) SetTitle(v string) {
	o.Title = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *GuestModel) GetGender() string {
	if o == nil || o.Gender == nil {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetGenderOk() (*string, bool) {
	if o == nil || o.Gender == nil {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *GuestModel) HasGender() bool {
	if o != nil && o.Gender != nil {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *GuestModel) SetGender(v string) {
	o.Gender = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *GuestModel) GetFirstName() string {
	if o == nil || o.FirstName == nil {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetFirstNameOk() (*string, bool) {
	if o == nil || o.FirstName == nil {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *GuestModel) HasFirstName() bool {
	if o != nil && o.FirstName != nil {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *GuestModel) SetFirstName(v string) {
	o.FirstName = &v
}

// GetMiddleInitial returns the MiddleInitial field value if set, zero value otherwise.
func (o *GuestModel) GetMiddleInitial() string {
	if o == nil || o.MiddleInitial == nil {
		var ret string
		return ret
	}
	return *o.MiddleInitial
}

// GetMiddleInitialOk returns a tuple with the MiddleInitial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetMiddleInitialOk() (*string, bool) {
	if o == nil || o.MiddleInitial == nil {
		return nil, false
	}
	return o.MiddleInitial, true
}

// HasMiddleInitial returns a boolean if a field has been set.
func (o *GuestModel) HasMiddleInitial() bool {
	if o != nil && o.MiddleInitial != nil {
		return true
	}

	return false
}

// SetMiddleInitial gets a reference to the given string and assigns it to the MiddleInitial field.
func (o *GuestModel) SetMiddleInitial(v string) {
	o.MiddleInitial = &v
}

// GetLastName returns the LastName field value
func (o *GuestModel) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *GuestModel) GetLastNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *GuestModel) SetLastName(v string) {
	o.LastName = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GuestModel) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GuestModel) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GuestModel) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *GuestModel) GetPhone() string {
	if o == nil || o.Phone == nil {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetPhoneOk() (*string, bool) {
	if o == nil || o.Phone == nil {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *GuestModel) HasPhone() bool {
	if o != nil && o.Phone != nil {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *GuestModel) SetPhone(v string) {
	o.Phone = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *GuestModel) GetAddress() PersonAddressModel {
	if o == nil || o.Address == nil {
		var ret PersonAddressModel
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetAddressOk() (*PersonAddressModel, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *GuestModel) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given PersonAddressModel and assigns it to the Address field.
func (o *GuestModel) SetAddress(v PersonAddressModel) {
	o.Address = &v
}

// GetNationalityCountryCode returns the NationalityCountryCode field value if set, zero value otherwise.
func (o *GuestModel) GetNationalityCountryCode() string {
	if o == nil || o.NationalityCountryCode == nil {
		var ret string
		return ret
	}
	return *o.NationalityCountryCode
}

// GetNationalityCountryCodeOk returns a tuple with the NationalityCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetNationalityCountryCodeOk() (*string, bool) {
	if o == nil || o.NationalityCountryCode == nil {
		return nil, false
	}
	return o.NationalityCountryCode, true
}

// HasNationalityCountryCode returns a boolean if a field has been set.
func (o *GuestModel) HasNationalityCountryCode() bool {
	if o != nil && o.NationalityCountryCode != nil {
		return true
	}

	return false
}

// SetNationalityCountryCode gets a reference to the given string and assigns it to the NationalityCountryCode field.
func (o *GuestModel) SetNationalityCountryCode(v string) {
	o.NationalityCountryCode = &v
}

// GetIdentificationNumber returns the IdentificationNumber field value if set, zero value otherwise.
func (o *GuestModel) GetIdentificationNumber() string {
	if o == nil || o.IdentificationNumber == nil {
		var ret string
		return ret
	}
	return *o.IdentificationNumber
}

// GetIdentificationNumberOk returns a tuple with the IdentificationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetIdentificationNumberOk() (*string, bool) {
	if o == nil || o.IdentificationNumber == nil {
		return nil, false
	}
	return o.IdentificationNumber, true
}

// HasIdentificationNumber returns a boolean if a field has been set.
func (o *GuestModel) HasIdentificationNumber() bool {
	if o != nil && o.IdentificationNumber != nil {
		return true
	}

	return false
}

// SetIdentificationNumber gets a reference to the given string and assigns it to the IdentificationNumber field.
func (o *GuestModel) SetIdentificationNumber(v string) {
	o.IdentificationNumber = &v
}

// GetIdentificationIssueDate returns the IdentificationIssueDate field value if set, zero value otherwise.
func (o *GuestModel) GetIdentificationIssueDate() string {
	if o == nil || o.IdentificationIssueDate == nil {
		var ret string
		return ret
	}
	return *o.IdentificationIssueDate
}

// GetIdentificationIssueDateOk returns a tuple with the IdentificationIssueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetIdentificationIssueDateOk() (*string, bool) {
	if o == nil || o.IdentificationIssueDate == nil {
		return nil, false
	}
	return o.IdentificationIssueDate, true
}

// HasIdentificationIssueDate returns a boolean if a field has been set.
func (o *GuestModel) HasIdentificationIssueDate() bool {
	if o != nil && o.IdentificationIssueDate != nil {
		return true
	}

	return false
}

// SetIdentificationIssueDate gets a reference to the given string and assigns it to the IdentificationIssueDate field.
func (o *GuestModel) SetIdentificationIssueDate(v string) {
	o.IdentificationIssueDate = &v
}

// GetIdentificationType returns the IdentificationType field value if set, zero value otherwise.
func (o *GuestModel) GetIdentificationType() string {
	if o == nil || o.IdentificationType == nil {
		var ret string
		return ret
	}
	return *o.IdentificationType
}

// GetIdentificationTypeOk returns a tuple with the IdentificationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetIdentificationTypeOk() (*string, bool) {
	if o == nil || o.IdentificationType == nil {
		return nil, false
	}
	return o.IdentificationType, true
}

// HasIdentificationType returns a boolean if a field has been set.
func (o *GuestModel) HasIdentificationType() bool {
	if o != nil && o.IdentificationType != nil {
		return true
	}

	return false
}

// SetIdentificationType gets a reference to the given string and assigns it to the IdentificationType field.
func (o *GuestModel) SetIdentificationType(v string) {
	o.IdentificationType = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *GuestModel) GetCompany() PersonCompanyModel {
	if o == nil || o.Company == nil {
		var ret PersonCompanyModel
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetCompanyOk() (*PersonCompanyModel, bool) {
	if o == nil || o.Company == nil {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *GuestModel) HasCompany() bool {
	if o != nil && o.Company != nil {
		return true
	}

	return false
}

// SetCompany gets a reference to the given PersonCompanyModel and assigns it to the Company field.
func (o *GuestModel) SetCompany(v PersonCompanyModel) {
	o.Company = &v
}

// GetPreferredLanguage returns the PreferredLanguage field value if set, zero value otherwise.
func (o *GuestModel) GetPreferredLanguage() string {
	if o == nil || o.PreferredLanguage == nil {
		var ret string
		return ret
	}
	return *o.PreferredLanguage
}

// GetPreferredLanguageOk returns a tuple with the PreferredLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetPreferredLanguageOk() (*string, bool) {
	if o == nil || o.PreferredLanguage == nil {
		return nil, false
	}
	return o.PreferredLanguage, true
}

// HasPreferredLanguage returns a boolean if a field has been set.
func (o *GuestModel) HasPreferredLanguage() bool {
	if o != nil && o.PreferredLanguage != nil {
		return true
	}

	return false
}

// SetPreferredLanguage gets a reference to the given string and assigns it to the PreferredLanguage field.
func (o *GuestModel) SetPreferredLanguage(v string) {
	o.PreferredLanguage = &v
}

// GetBirthDate returns the BirthDate field value if set, zero value otherwise.
func (o *GuestModel) GetBirthDate() string {
	if o == nil || o.BirthDate == nil {
		var ret string
		return ret
	}
	return *o.BirthDate
}

// GetBirthDateOk returns a tuple with the BirthDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetBirthDateOk() (*string, bool) {
	if o == nil || o.BirthDate == nil {
		return nil, false
	}
	return o.BirthDate, true
}

// HasBirthDate returns a boolean if a field has been set.
func (o *GuestModel) HasBirthDate() bool {
	if o != nil && o.BirthDate != nil {
		return true
	}

	return false
}

// SetBirthDate gets a reference to the given string and assigns it to the BirthDate field.
func (o *GuestModel) SetBirthDate(v string) {
	o.BirthDate = &v
}

// GetBirthPlace returns the BirthPlace field value if set, zero value otherwise.
func (o *GuestModel) GetBirthPlace() string {
	if o == nil || o.BirthPlace == nil {
		var ret string
		return ret
	}
	return *o.BirthPlace
}

// GetBirthPlaceOk returns a tuple with the BirthPlace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestModel) GetBirthPlaceOk() (*string, bool) {
	if o == nil || o.BirthPlace == nil {
		return nil, false
	}
	return o.BirthPlace, true
}

// HasBirthPlace returns a boolean if a field has been set.
func (o *GuestModel) HasBirthPlace() bool {
	if o != nil && o.BirthPlace != nil {
		return true
	}

	return false
}

// SetBirthPlace gets a reference to the given string and assigns it to the BirthPlace field.
func (o *GuestModel) SetBirthPlace(v string) {
	o.BirthPlace = &v
}

func (o GuestModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Gender != nil {
		toSerialize["gender"] = o.Gender
	}
	if o.FirstName != nil {
		toSerialize["firstName"] = o.FirstName
	}
	if o.MiddleInitial != nil {
		toSerialize["middleInitial"] = o.MiddleInitial
	}
	if true {
		toSerialize["lastName"] = o.LastName
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Phone != nil {
		toSerialize["phone"] = o.Phone
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.NationalityCountryCode != nil {
		toSerialize["nationalityCountryCode"] = o.NationalityCountryCode
	}
	if o.IdentificationNumber != nil {
		toSerialize["identificationNumber"] = o.IdentificationNumber
	}
	if o.IdentificationIssueDate != nil {
		toSerialize["identificationIssueDate"] = o.IdentificationIssueDate
	}
	if o.IdentificationType != nil {
		toSerialize["identificationType"] = o.IdentificationType
	}
	if o.Company != nil {
		toSerialize["company"] = o.Company
	}
	if o.PreferredLanguage != nil {
		toSerialize["preferredLanguage"] = o.PreferredLanguage
	}
	if o.BirthDate != nil {
		toSerialize["birthDate"] = o.BirthDate
	}
	if o.BirthPlace != nil {
		toSerialize["birthPlace"] = o.BirthPlace
	}
	return json.Marshal(toSerialize)
}

type NullableGuestModel struct {
	value *GuestModel
	isSet bool
}

func (v NullableGuestModel) Get() *GuestModel {
	return v.value
}

func (v *NullableGuestModel) Set(val *GuestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGuestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGuestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuestModel(val *GuestModel) *NullableGuestModel {
	return &NullableGuestModel{value: val, isSet: true}
}

func (v NullableGuestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


