/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// EmbeddedGroupModel struct for EmbeddedGroupModel
type EmbeddedGroupModel struct {
	// Group booking id
	Id string `json:"id"`
	// Name of the group
	Name *string `json:"name,omitempty"`
}

// NewEmbeddedGroupModel instantiates a new EmbeddedGroupModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedGroupModel(id string) *EmbeddedGroupModel {
	this := EmbeddedGroupModel{}
	this.Id = id
	return &this
}

// NewEmbeddedGroupModelWithDefaults instantiates a new EmbeddedGroupModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedGroupModelWithDefaults() *EmbeddedGroupModel {
	this := EmbeddedGroupModel{}
	return &this
}

// GetId returns the Id field value
func (o *EmbeddedGroupModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmbeddedGroupModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmbeddedGroupModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmbeddedGroupModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedGroupModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmbeddedGroupModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmbeddedGroupModel) SetName(v string) {
	o.Name = &v
}

func (o EmbeddedGroupModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedGroupModel struct {
	value *EmbeddedGroupModel
	isSet bool
}

func (v NullableEmbeddedGroupModel) Get() *EmbeddedGroupModel {
	return v.value
}

func (v *NullableEmbeddedGroupModel) Set(val *EmbeddedGroupModel) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedGroupModel) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedGroupModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedGroupModel(val *EmbeddedGroupModel) *NullableEmbeddedGroupModel {
	return &NullableEmbeddedGroupModel{value: val, isSet: true}
}

func (v NullableEmbeddedGroupModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedGroupModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


