/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// TimeSliceListModel struct for TimeSliceListModel
type TimeSliceListModel struct {
	// List of time slices
	TimeSlices *[]TimeSliceItemModel `json:"timeSlices,omitempty"`
	// Total count of items
	Count int64 `json:"count"`
}

// NewTimeSliceListModel instantiates a new TimeSliceListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeSliceListModel(count int64) *TimeSliceListModel {
	this := TimeSliceListModel{}
	this.Count = count
	return &this
}

// NewTimeSliceListModelWithDefaults instantiates a new TimeSliceListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeSliceListModelWithDefaults() *TimeSliceListModel {
	this := TimeSliceListModel{}
	return &this
}

// GetTimeSlices returns the TimeSlices field value if set, zero value otherwise.
func (o *TimeSliceListModel) GetTimeSlices() []TimeSliceItemModel {
	if o == nil || o.TimeSlices == nil {
		var ret []TimeSliceItemModel
		return ret
	}
	return *o.TimeSlices
}

// GetTimeSlicesOk returns a tuple with the TimeSlices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeSliceListModel) GetTimeSlicesOk() (*[]TimeSliceItemModel, bool) {
	if o == nil || o.TimeSlices == nil {
		return nil, false
	}
	return o.TimeSlices, true
}

// HasTimeSlices returns a boolean if a field has been set.
func (o *TimeSliceListModel) HasTimeSlices() bool {
	if o != nil && o.TimeSlices != nil {
		return true
	}

	return false
}

// SetTimeSlices gets a reference to the given []TimeSliceItemModel and assigns it to the TimeSlices field.
func (o *TimeSliceListModel) SetTimeSlices(v []TimeSliceItemModel) {
	o.TimeSlices = &v
}

// GetCount returns the Count field value
func (o *TimeSliceListModel) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TimeSliceListModel) GetCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TimeSliceListModel) SetCount(v int64) {
	o.Count = v
}

func (o TimeSliceListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TimeSlices != nil {
		toSerialize["timeSlices"] = o.TimeSlices
	}
	if true {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableTimeSliceListModel struct {
	value *TimeSliceListModel
	isSet bool
}

func (v NullableTimeSliceListModel) Get() *TimeSliceListModel {
	return v.value
}

func (v *NullableTimeSliceListModel) Set(val *TimeSliceListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeSliceListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeSliceListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeSliceListModel(val *TimeSliceListModel) *NullableTimeSliceListModel {
	return &NullableTimeSliceListModel{value: val, isSet: true}
}

func (v NullableTimeSliceListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeSliceListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


