/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// EmbeddedRatePlanModel struct for EmbeddedRatePlanModel
type EmbeddedRatePlanModel struct {
	// The rate plan id
	Id string `json:"id"`
	// The code for the rate plan that can be shown in reports and table views
	Code *string `json:"code,omitempty"`
	// The name for the rate plan
	Name *string `json:"name,omitempty"`
	// The description for the rate plan
	Description *string `json:"description,omitempty"`
	// Whether the rate plan is subject to city tax or not
	IsSubjectToCityTax bool `json:"isSubjectToCityTax"`
}

// NewEmbeddedRatePlanModel instantiates a new EmbeddedRatePlanModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedRatePlanModel(id string, isSubjectToCityTax bool) *EmbeddedRatePlanModel {
	this := EmbeddedRatePlanModel{}
	this.Id = id
	this.IsSubjectToCityTax = isSubjectToCityTax
	return &this
}

// NewEmbeddedRatePlanModelWithDefaults instantiates a new EmbeddedRatePlanModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedRatePlanModelWithDefaults() *EmbeddedRatePlanModel {
	this := EmbeddedRatePlanModel{}
	return &this
}

// GetId returns the Id field value
func (o *EmbeddedRatePlanModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmbeddedRatePlanModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmbeddedRatePlanModel) SetId(v string) {
	o.Id = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *EmbeddedRatePlanModel) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedRatePlanModel) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *EmbeddedRatePlanModel) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *EmbeddedRatePlanModel) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmbeddedRatePlanModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedRatePlanModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmbeddedRatePlanModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmbeddedRatePlanModel) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EmbeddedRatePlanModel) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedRatePlanModel) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EmbeddedRatePlanModel) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EmbeddedRatePlanModel) SetDescription(v string) {
	o.Description = &v
}

// GetIsSubjectToCityTax returns the IsSubjectToCityTax field value
func (o *EmbeddedRatePlanModel) GetIsSubjectToCityTax() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSubjectToCityTax
}

// GetIsSubjectToCityTaxOk returns a tuple with the IsSubjectToCityTax field value
// and a boolean to check if the value has been set.
func (o *EmbeddedRatePlanModel) GetIsSubjectToCityTaxOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsSubjectToCityTax, true
}

// SetIsSubjectToCityTax sets field value
func (o *EmbeddedRatePlanModel) SetIsSubjectToCityTax(v bool) {
	o.IsSubjectToCityTax = v
}

func (o EmbeddedRatePlanModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["isSubjectToCityTax"] = o.IsSubjectToCityTax
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedRatePlanModel struct {
	value *EmbeddedRatePlanModel
	isSet bool
}

func (v NullableEmbeddedRatePlanModel) Get() *EmbeddedRatePlanModel {
	return v.value
}

func (v *NullableEmbeddedRatePlanModel) Set(val *EmbeddedRatePlanModel) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedRatePlanModel) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedRatePlanModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedRatePlanModel(val *EmbeddedRatePlanModel) *NullableEmbeddedRatePlanModel {
	return &NullableEmbeddedRatePlanModel{value: val, isSet: true}
}

func (v NullableEmbeddedRatePlanModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedRatePlanModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


