/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
	"time"
)

// BlockModel struct for BlockModel
type BlockModel struct {
	// Block id
	Id string `json:"id"`
	Group EmbeddedGroupModel `json:"group"`
	// Status of the block. Tentative will just mark inventory as requested, but still allows to sell it  through other channels. Definite will block the inventory for selling through other channels
	Status string `json:"status"`
	Property EmbeddedPropertyModel `json:"property"`
	RatePlan EmbeddedRatePlanModel `json:"ratePlan"`
	UnitGroup EmbeddedUnitGroupModel `json:"unitGroup"`
	GrossDailyRate MonetaryValueModel `json:"grossDailyRate"`
	// Start date and time from which the inventory will be blocked<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	From time.Time `json:"from"`
	// End date and time until which the inventory will be blocked<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	To time.Time `json:"to"`
	// Number of reservations already picked from this block
	PickedReservations int32 `json:"pickedReservations"`
	// The promo code associated with a certain special offer used to create the block
	PromoCode *string `json:"promoCode,omitempty"`
	// The corporate code associated with a certain special offer used to create the block
	CorporateCode *string `json:"corporateCode,omitempty"`
	// Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Created time.Time `json:"created"`
	// Date of last modification<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Modified time.Time `json:"modified"`
	// The list of time slices for this block
	TimeSlices *[]BlockTimeSliceModel `json:"timeSlices,omitempty"`
	// The list of actions for this block
	Actions *[]ActionModelBlockActionNotAllowedBlockActionReason `json:"actions,omitempty"`
}

// NewBlockModel instantiates a new BlockModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockModel(id string, group EmbeddedGroupModel, status string, property EmbeddedPropertyModel, ratePlan EmbeddedRatePlanModel, unitGroup EmbeddedUnitGroupModel, grossDailyRate MonetaryValueModel, from time.Time, to time.Time, pickedReservations int32, created time.Time, modified time.Time) *BlockModel {
	this := BlockModel{}
	this.Id = id
	this.Group = group
	this.Status = status
	this.Property = property
	this.RatePlan = ratePlan
	this.UnitGroup = unitGroup
	this.GrossDailyRate = grossDailyRate
	this.From = from
	this.To = to
	this.PickedReservations = pickedReservations
	this.Created = created
	this.Modified = modified
	return &this
}

// NewBlockModelWithDefaults instantiates a new BlockModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockModelWithDefaults() *BlockModel {
	this := BlockModel{}
	return &this
}

// GetId returns the Id field value
func (o *BlockModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BlockModel) SetId(v string) {
	o.Id = v
}

// GetGroup returns the Group field value
func (o *BlockModel) GetGroup() EmbeddedGroupModel {
	if o == nil {
		var ret EmbeddedGroupModel
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetGroupOk() (*EmbeddedGroupModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *BlockModel) SetGroup(v EmbeddedGroupModel) {
	o.Group = v
}

// GetStatus returns the Status field value
func (o *BlockModel) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BlockModel) SetStatus(v string) {
	o.Status = v
}

// GetProperty returns the Property field value
func (o *BlockModel) GetProperty() EmbeddedPropertyModel {
	if o == nil {
		var ret EmbeddedPropertyModel
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetPropertyOk() (*EmbeddedPropertyModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *BlockModel) SetProperty(v EmbeddedPropertyModel) {
	o.Property = v
}

// GetRatePlan returns the RatePlan field value
func (o *BlockModel) GetRatePlan() EmbeddedRatePlanModel {
	if o == nil {
		var ret EmbeddedRatePlanModel
		return ret
	}

	return o.RatePlan
}

// GetRatePlanOk returns a tuple with the RatePlan field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetRatePlanOk() (*EmbeddedRatePlanModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RatePlan, true
}

// SetRatePlan sets field value
func (o *BlockModel) SetRatePlan(v EmbeddedRatePlanModel) {
	o.RatePlan = v
}

// GetUnitGroup returns the UnitGroup field value
func (o *BlockModel) GetUnitGroup() EmbeddedUnitGroupModel {
	if o == nil {
		var ret EmbeddedUnitGroupModel
		return ret
	}

	return o.UnitGroup
}

// GetUnitGroupOk returns a tuple with the UnitGroup field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetUnitGroupOk() (*EmbeddedUnitGroupModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnitGroup, true
}

// SetUnitGroup sets field value
func (o *BlockModel) SetUnitGroup(v EmbeddedUnitGroupModel) {
	o.UnitGroup = v
}

// GetGrossDailyRate returns the GrossDailyRate field value
func (o *BlockModel) GetGrossDailyRate() MonetaryValueModel {
	if o == nil {
		var ret MonetaryValueModel
		return ret
	}

	return o.GrossDailyRate
}

// GetGrossDailyRateOk returns a tuple with the GrossDailyRate field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetGrossDailyRateOk() (*MonetaryValueModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GrossDailyRate, true
}

// SetGrossDailyRate sets field value
func (o *BlockModel) SetGrossDailyRate(v MonetaryValueModel) {
	o.GrossDailyRate = v
}

// GetFrom returns the From field value
func (o *BlockModel) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetFromOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *BlockModel) SetFrom(v time.Time) {
	o.From = v
}

// GetTo returns the To field value
func (o *BlockModel) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetToOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *BlockModel) SetTo(v time.Time) {
	o.To = v
}

// GetPickedReservations returns the PickedReservations field value
func (o *BlockModel) GetPickedReservations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PickedReservations
}

// GetPickedReservationsOk returns a tuple with the PickedReservations field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetPickedReservationsOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PickedReservations, true
}

// SetPickedReservations sets field value
func (o *BlockModel) SetPickedReservations(v int32) {
	o.PickedReservations = v
}

// GetPromoCode returns the PromoCode field value if set, zero value otherwise.
func (o *BlockModel) GetPromoCode() string {
	if o == nil || o.PromoCode == nil {
		var ret string
		return ret
	}
	return *o.PromoCode
}

// GetPromoCodeOk returns a tuple with the PromoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockModel) GetPromoCodeOk() (*string, bool) {
	if o == nil || o.PromoCode == nil {
		return nil, false
	}
	return o.PromoCode, true
}

// HasPromoCode returns a boolean if a field has been set.
func (o *BlockModel) HasPromoCode() bool {
	if o != nil && o.PromoCode != nil {
		return true
	}

	return false
}

// SetPromoCode gets a reference to the given string and assigns it to the PromoCode field.
func (o *BlockModel) SetPromoCode(v string) {
	o.PromoCode = &v
}

// GetCorporateCode returns the CorporateCode field value if set, zero value otherwise.
func (o *BlockModel) GetCorporateCode() string {
	if o == nil || o.CorporateCode == nil {
		var ret string
		return ret
	}
	return *o.CorporateCode
}

// GetCorporateCodeOk returns a tuple with the CorporateCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockModel) GetCorporateCodeOk() (*string, bool) {
	if o == nil || o.CorporateCode == nil {
		return nil, false
	}
	return o.CorporateCode, true
}

// HasCorporateCode returns a boolean if a field has been set.
func (o *BlockModel) HasCorporateCode() bool {
	if o != nil && o.CorporateCode != nil {
		return true
	}

	return false
}

// SetCorporateCode gets a reference to the given string and assigns it to the CorporateCode field.
func (o *BlockModel) SetCorporateCode(v string) {
	o.CorporateCode = &v
}

// GetCreated returns the Created field value
func (o *BlockModel) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetCreatedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *BlockModel) SetCreated(v time.Time) {
	o.Created = v
}

// GetModified returns the Modified field value
func (o *BlockModel) GetModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value
// and a boolean to check if the value has been set.
func (o *BlockModel) GetModifiedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Modified, true
}

// SetModified sets field value
func (o *BlockModel) SetModified(v time.Time) {
	o.Modified = v
}

// GetTimeSlices returns the TimeSlices field value if set, zero value otherwise.
func (o *BlockModel) GetTimeSlices() []BlockTimeSliceModel {
	if o == nil || o.TimeSlices == nil {
		var ret []BlockTimeSliceModel
		return ret
	}
	return *o.TimeSlices
}

// GetTimeSlicesOk returns a tuple with the TimeSlices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockModel) GetTimeSlicesOk() (*[]BlockTimeSliceModel, bool) {
	if o == nil || o.TimeSlices == nil {
		return nil, false
	}
	return o.TimeSlices, true
}

// HasTimeSlices returns a boolean if a field has been set.
func (o *BlockModel) HasTimeSlices() bool {
	if o != nil && o.TimeSlices != nil {
		return true
	}

	return false
}

// SetTimeSlices gets a reference to the given []BlockTimeSliceModel and assigns it to the TimeSlices field.
func (o *BlockModel) SetTimeSlices(v []BlockTimeSliceModel) {
	o.TimeSlices = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *BlockModel) GetActions() []ActionModelBlockActionNotAllowedBlockActionReason {
	if o == nil || o.Actions == nil {
		var ret []ActionModelBlockActionNotAllowedBlockActionReason
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockModel) GetActionsOk() (*[]ActionModelBlockActionNotAllowedBlockActionReason, bool) {
	if o == nil || o.Actions == nil {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *BlockModel) HasActions() bool {
	if o != nil && o.Actions != nil {
		return true
	}

	return false
}

// SetActions gets a reference to the given []ActionModelBlockActionNotAllowedBlockActionReason and assigns it to the Actions field.
func (o *BlockModel) SetActions(v []ActionModelBlockActionNotAllowedBlockActionReason) {
	o.Actions = &v
}

func (o BlockModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["group"] = o.Group
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["property"] = o.Property
	}
	if true {
		toSerialize["ratePlan"] = o.RatePlan
	}
	if true {
		toSerialize["unitGroup"] = o.UnitGroup
	}
	if true {
		toSerialize["grossDailyRate"] = o.GrossDailyRate
	}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["pickedReservations"] = o.PickedReservations
	}
	if o.PromoCode != nil {
		toSerialize["promoCode"] = o.PromoCode
	}
	if o.CorporateCode != nil {
		toSerialize["corporateCode"] = o.CorporateCode
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["modified"] = o.Modified
	}
	if o.TimeSlices != nil {
		toSerialize["timeSlices"] = o.TimeSlices
	}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	return json.Marshal(toSerialize)
}

type NullableBlockModel struct {
	value *BlockModel
	isSet bool
}

func (v NullableBlockModel) Get() *BlockModel {
	return v.value
}

func (v *NullableBlockModel) Set(val *BlockModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockModel(val *BlockModel) *NullableBlockModel {
	return &NullableBlockModel{value: val, isSet: true}
}

func (v NullableBlockModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


