/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
	"time"
)

// ReservationAssignedUnitTimeRangeModel struct for ReservationAssignedUnitTimeRangeModel
type ReservationAssignedUnitTimeRangeModel struct {
	// The start date and time of the period for which the unit is assigned to the reservation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	From time.Time `json:"from"`
	// The end date and time of the period for which the unit is assigned to the reservation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	To time.Time `json:"to"`
}

// NewReservationAssignedUnitTimeRangeModel instantiates a new ReservationAssignedUnitTimeRangeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationAssignedUnitTimeRangeModel(from time.Time, to time.Time) *ReservationAssignedUnitTimeRangeModel {
	this := ReservationAssignedUnitTimeRangeModel{}
	this.From = from
	this.To = to
	return &this
}

// NewReservationAssignedUnitTimeRangeModelWithDefaults instantiates a new ReservationAssignedUnitTimeRangeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationAssignedUnitTimeRangeModelWithDefaults() *ReservationAssignedUnitTimeRangeModel {
	this := ReservationAssignedUnitTimeRangeModel{}
	return &this
}

// GetFrom returns the From field value
func (o *ReservationAssignedUnitTimeRangeModel) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *ReservationAssignedUnitTimeRangeModel) GetFromOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *ReservationAssignedUnitTimeRangeModel) SetFrom(v time.Time) {
	o.From = v
}

// GetTo returns the To field value
func (o *ReservationAssignedUnitTimeRangeModel) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ReservationAssignedUnitTimeRangeModel) GetToOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ReservationAssignedUnitTimeRangeModel) SetTo(v time.Time) {
	o.To = v
}

func (o ReservationAssignedUnitTimeRangeModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableReservationAssignedUnitTimeRangeModel struct {
	value *ReservationAssignedUnitTimeRangeModel
	isSet bool
}

func (v NullableReservationAssignedUnitTimeRangeModel) Get() *ReservationAssignedUnitTimeRangeModel {
	return v.value
}

func (v *NullableReservationAssignedUnitTimeRangeModel) Set(val *ReservationAssignedUnitTimeRangeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationAssignedUnitTimeRangeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationAssignedUnitTimeRangeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationAssignedUnitTimeRangeModel(val *ReservationAssignedUnitTimeRangeModel) *NullableReservationAssignedUnitTimeRangeModel {
	return &NullableReservationAssignedUnitTimeRangeModel{value: val, isSet: true}
}

func (v NullableReservationAssignedUnitTimeRangeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationAssignedUnitTimeRangeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


