/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// PickUpReservationsModel With this request you can pick up reservations to an existing group booking
type PickUpReservationsModel struct {
	// List of reservations to pick up to the existing group booking
	Reservations []PickUpReservationModel `json:"reservations"`
}

// NewPickUpReservationsModel instantiates a new PickUpReservationsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickUpReservationsModel(reservations []PickUpReservationModel) *PickUpReservationsModel {
	this := PickUpReservationsModel{}
	this.Reservations = reservations
	return &this
}

// NewPickUpReservationsModelWithDefaults instantiates a new PickUpReservationsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickUpReservationsModelWithDefaults() *PickUpReservationsModel {
	this := PickUpReservationsModel{}
	return &this
}

// GetReservations returns the Reservations field value
func (o *PickUpReservationsModel) GetReservations() []PickUpReservationModel {
	if o == nil {
		var ret []PickUpReservationModel
		return ret
	}

	return o.Reservations
}

// GetReservationsOk returns a tuple with the Reservations field value
// and a boolean to check if the value has been set.
func (o *PickUpReservationsModel) GetReservationsOk() (*[]PickUpReservationModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Reservations, true
}

// SetReservations sets field value
func (o *PickUpReservationsModel) SetReservations(v []PickUpReservationModel) {
	o.Reservations = v
}

func (o PickUpReservationsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["reservations"] = o.Reservations
	}
	return json.Marshal(toSerialize)
}

type NullablePickUpReservationsModel struct {
	value *PickUpReservationsModel
	isSet bool
}

func (v NullablePickUpReservationsModel) Get() *PickUpReservationsModel {
	return v.value
}

func (v *NullablePickUpReservationsModel) Set(val *PickUpReservationsModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePickUpReservationsModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePickUpReservationsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickUpReservationsModel(val *PickUpReservationsModel) *NullablePickUpReservationsModel {
	return &NullablePickUpReservationsModel{value: val, isSet: true}
}

func (v NullablePickUpReservationsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickUpReservationsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


