/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
	"time"
)

// BookingReservationModel struct for BookingReservationModel
type BookingReservationModel struct {
	// Reservation id
	Id string `json:"id"`
	// Status of the reservation
	Status string `json:"status"`
	// Code in external system
	ExternalCode *string `json:"externalCode,omitempty"`
	// Channel code
	ChannelCode string `json:"channelCode"`
	// Source of the reservation (e.g Hotels.com, Orbitz, etc.)
	Source *string `json:"source,omitempty"`
	PaymentAccount *PaymentAccountModel `json:"paymentAccount,omitempty"`
	// Date of arrival<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Arrival time.Time `json:"arrival"`
	// Date of departure<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Departure time.Time `json:"departure"`
	// Number of adults
	Adults int32 `json:"adults"`
	// The ages of the children
	ChildrenAges *[]int32 `json:"childrenAges,omitempty"`
	TotalGrossAmount MonetaryValueModel `json:"totalGrossAmount"`
	Property EmbeddedPropertyModel `json:"property"`
	RatePlan EmbeddedRatePlanModel `json:"ratePlan"`
	UnitGroup EmbeddedUnitGroupModel `json:"unitGroup"`
	// The list of additional services (extras, add-ons) reserved for the stay
	Services *[]ReservationServiceItemModel `json:"services,omitempty"`
	// Additional information and comment by the guest
	GuestComment *string `json:"guestComment,omitempty"`
	CancellationFee ReservationCancellationFeeModel `json:"cancellationFee"`
	NoShowFee ReservationNoShowFeeModel `json:"noShowFee"`
	Company *EmbeddedCompanyModel `json:"company,omitempty"`
}

// NewBookingReservationModel instantiates a new BookingReservationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookingReservationModel(id string, status string, channelCode string, arrival time.Time, departure time.Time, adults int32, totalGrossAmount MonetaryValueModel, property EmbeddedPropertyModel, ratePlan EmbeddedRatePlanModel, unitGroup EmbeddedUnitGroupModel, cancellationFee ReservationCancellationFeeModel, noShowFee ReservationNoShowFeeModel) *BookingReservationModel {
	this := BookingReservationModel{}
	this.Id = id
	this.Status = status
	this.ChannelCode = channelCode
	this.Arrival = arrival
	this.Departure = departure
	this.Adults = adults
	this.TotalGrossAmount = totalGrossAmount
	this.Property = property
	this.RatePlan = ratePlan
	this.UnitGroup = unitGroup
	this.CancellationFee = cancellationFee
	this.NoShowFee = noShowFee
	return &this
}

// NewBookingReservationModelWithDefaults instantiates a new BookingReservationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookingReservationModelWithDefaults() *BookingReservationModel {
	this := BookingReservationModel{}
	return &this
}

// GetId returns the Id field value
func (o *BookingReservationModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BookingReservationModel) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *BookingReservationModel) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BookingReservationModel) SetStatus(v string) {
	o.Status = v
}

// GetExternalCode returns the ExternalCode field value if set, zero value otherwise.
func (o *BookingReservationModel) GetExternalCode() string {
	if o == nil || o.ExternalCode == nil {
		var ret string
		return ret
	}
	return *o.ExternalCode
}

// GetExternalCodeOk returns a tuple with the ExternalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetExternalCodeOk() (*string, bool) {
	if o == nil || o.ExternalCode == nil {
		return nil, false
	}
	return o.ExternalCode, true
}

// HasExternalCode returns a boolean if a field has been set.
func (o *BookingReservationModel) HasExternalCode() bool {
	if o != nil && o.ExternalCode != nil {
		return true
	}

	return false
}

// SetExternalCode gets a reference to the given string and assigns it to the ExternalCode field.
func (o *BookingReservationModel) SetExternalCode(v string) {
	o.ExternalCode = &v
}

// GetChannelCode returns the ChannelCode field value
func (o *BookingReservationModel) GetChannelCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetChannelCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *BookingReservationModel) SetChannelCode(v string) {
	o.ChannelCode = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *BookingReservationModel) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *BookingReservationModel) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *BookingReservationModel) SetSource(v string) {
	o.Source = &v
}

// GetPaymentAccount returns the PaymentAccount field value if set, zero value otherwise.
func (o *BookingReservationModel) GetPaymentAccount() PaymentAccountModel {
	if o == nil || o.PaymentAccount == nil {
		var ret PaymentAccountModel
		return ret
	}
	return *o.PaymentAccount
}

// GetPaymentAccountOk returns a tuple with the PaymentAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetPaymentAccountOk() (*PaymentAccountModel, bool) {
	if o == nil || o.PaymentAccount == nil {
		return nil, false
	}
	return o.PaymentAccount, true
}

// HasPaymentAccount returns a boolean if a field has been set.
func (o *BookingReservationModel) HasPaymentAccount() bool {
	if o != nil && o.PaymentAccount != nil {
		return true
	}

	return false
}

// SetPaymentAccount gets a reference to the given PaymentAccountModel and assigns it to the PaymentAccount field.
func (o *BookingReservationModel) SetPaymentAccount(v PaymentAccountModel) {
	o.PaymentAccount = &v
}

// GetArrival returns the Arrival field value
func (o *BookingReservationModel) GetArrival() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Arrival
}

// GetArrivalOk returns a tuple with the Arrival field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetArrivalOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Arrival, true
}

// SetArrival sets field value
func (o *BookingReservationModel) SetArrival(v time.Time) {
	o.Arrival = v
}

// GetDeparture returns the Departure field value
func (o *BookingReservationModel) GetDeparture() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Departure
}

// GetDepartureOk returns a tuple with the Departure field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetDepartureOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Departure, true
}

// SetDeparture sets field value
func (o *BookingReservationModel) SetDeparture(v time.Time) {
	o.Departure = v
}

// GetAdults returns the Adults field value
func (o *BookingReservationModel) GetAdults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Adults
}

// GetAdultsOk returns a tuple with the Adults field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetAdultsOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Adults, true
}

// SetAdults sets field value
func (o *BookingReservationModel) SetAdults(v int32) {
	o.Adults = v
}

// GetChildrenAges returns the ChildrenAges field value if set, zero value otherwise.
func (o *BookingReservationModel) GetChildrenAges() []int32 {
	if o == nil || o.ChildrenAges == nil {
		var ret []int32
		return ret
	}
	return *o.ChildrenAges
}

// GetChildrenAgesOk returns a tuple with the ChildrenAges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetChildrenAgesOk() (*[]int32, bool) {
	if o == nil || o.ChildrenAges == nil {
		return nil, false
	}
	return o.ChildrenAges, true
}

// HasChildrenAges returns a boolean if a field has been set.
func (o *BookingReservationModel) HasChildrenAges() bool {
	if o != nil && o.ChildrenAges != nil {
		return true
	}

	return false
}

// SetChildrenAges gets a reference to the given []int32 and assigns it to the ChildrenAges field.
func (o *BookingReservationModel) SetChildrenAges(v []int32) {
	o.ChildrenAges = &v
}

// GetTotalGrossAmount returns the TotalGrossAmount field value
func (o *BookingReservationModel) GetTotalGrossAmount() MonetaryValueModel {
	if o == nil {
		var ret MonetaryValueModel
		return ret
	}

	return o.TotalGrossAmount
}

// GetTotalGrossAmountOk returns a tuple with the TotalGrossAmount field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetTotalGrossAmountOk() (*MonetaryValueModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalGrossAmount, true
}

// SetTotalGrossAmount sets field value
func (o *BookingReservationModel) SetTotalGrossAmount(v MonetaryValueModel) {
	o.TotalGrossAmount = v
}

// GetProperty returns the Property field value
func (o *BookingReservationModel) GetProperty() EmbeddedPropertyModel {
	if o == nil {
		var ret EmbeddedPropertyModel
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetPropertyOk() (*EmbeddedPropertyModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *BookingReservationModel) SetProperty(v EmbeddedPropertyModel) {
	o.Property = v
}

// GetRatePlan returns the RatePlan field value
func (o *BookingReservationModel) GetRatePlan() EmbeddedRatePlanModel {
	if o == nil {
		var ret EmbeddedRatePlanModel
		return ret
	}

	return o.RatePlan
}

// GetRatePlanOk returns a tuple with the RatePlan field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetRatePlanOk() (*EmbeddedRatePlanModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RatePlan, true
}

// SetRatePlan sets field value
func (o *BookingReservationModel) SetRatePlan(v EmbeddedRatePlanModel) {
	o.RatePlan = v
}

// GetUnitGroup returns the UnitGroup field value
func (o *BookingReservationModel) GetUnitGroup() EmbeddedUnitGroupModel {
	if o == nil {
		var ret EmbeddedUnitGroupModel
		return ret
	}

	return o.UnitGroup
}

// GetUnitGroupOk returns a tuple with the UnitGroup field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetUnitGroupOk() (*EmbeddedUnitGroupModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnitGroup, true
}

// SetUnitGroup sets field value
func (o *BookingReservationModel) SetUnitGroup(v EmbeddedUnitGroupModel) {
	o.UnitGroup = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *BookingReservationModel) GetServices() []ReservationServiceItemModel {
	if o == nil || o.Services == nil {
		var ret []ReservationServiceItemModel
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetServicesOk() (*[]ReservationServiceItemModel, bool) {
	if o == nil || o.Services == nil {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *BookingReservationModel) HasServices() bool {
	if o != nil && o.Services != nil {
		return true
	}

	return false
}

// SetServices gets a reference to the given []ReservationServiceItemModel and assigns it to the Services field.
func (o *BookingReservationModel) SetServices(v []ReservationServiceItemModel) {
	o.Services = &v
}

// GetGuestComment returns the GuestComment field value if set, zero value otherwise.
func (o *BookingReservationModel) GetGuestComment() string {
	if o == nil || o.GuestComment == nil {
		var ret string
		return ret
	}
	return *o.GuestComment
}

// GetGuestCommentOk returns a tuple with the GuestComment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetGuestCommentOk() (*string, bool) {
	if o == nil || o.GuestComment == nil {
		return nil, false
	}
	return o.GuestComment, true
}

// HasGuestComment returns a boolean if a field has been set.
func (o *BookingReservationModel) HasGuestComment() bool {
	if o != nil && o.GuestComment != nil {
		return true
	}

	return false
}

// SetGuestComment gets a reference to the given string and assigns it to the GuestComment field.
func (o *BookingReservationModel) SetGuestComment(v string) {
	o.GuestComment = &v
}

// GetCancellationFee returns the CancellationFee field value
func (o *BookingReservationModel) GetCancellationFee() ReservationCancellationFeeModel {
	if o == nil {
		var ret ReservationCancellationFeeModel
		return ret
	}

	return o.CancellationFee
}

// GetCancellationFeeOk returns a tuple with the CancellationFee field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetCancellationFeeOk() (*ReservationCancellationFeeModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CancellationFee, true
}

// SetCancellationFee sets field value
func (o *BookingReservationModel) SetCancellationFee(v ReservationCancellationFeeModel) {
	o.CancellationFee = v
}

// GetNoShowFee returns the NoShowFee field value
func (o *BookingReservationModel) GetNoShowFee() ReservationNoShowFeeModel {
	if o == nil {
		var ret ReservationNoShowFeeModel
		return ret
	}

	return o.NoShowFee
}

// GetNoShowFeeOk returns a tuple with the NoShowFee field value
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetNoShowFeeOk() (*ReservationNoShowFeeModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NoShowFee, true
}

// SetNoShowFee sets field value
func (o *BookingReservationModel) SetNoShowFee(v ReservationNoShowFeeModel) {
	o.NoShowFee = v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *BookingReservationModel) GetCompany() EmbeddedCompanyModel {
	if o == nil || o.Company == nil {
		var ret EmbeddedCompanyModel
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookingReservationModel) GetCompanyOk() (*EmbeddedCompanyModel, bool) {
	if o == nil || o.Company == nil {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *BookingReservationModel) HasCompany() bool {
	if o != nil && o.Company != nil {
		return true
	}

	return false
}

// SetCompany gets a reference to the given EmbeddedCompanyModel and assigns it to the Company field.
func (o *BookingReservationModel) SetCompany(v EmbeddedCompanyModel) {
	o.Company = &v
}

func (o BookingReservationModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.ExternalCode != nil {
		toSerialize["externalCode"] = o.ExternalCode
	}
	if true {
		toSerialize["channelCode"] = o.ChannelCode
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.PaymentAccount != nil {
		toSerialize["paymentAccount"] = o.PaymentAccount
	}
	if true {
		toSerialize["arrival"] = o.Arrival
	}
	if true {
		toSerialize["departure"] = o.Departure
	}
	if true {
		toSerialize["adults"] = o.Adults
	}
	if o.ChildrenAges != nil {
		toSerialize["childrenAges"] = o.ChildrenAges
	}
	if true {
		toSerialize["totalGrossAmount"] = o.TotalGrossAmount
	}
	if true {
		toSerialize["property"] = o.Property
	}
	if true {
		toSerialize["ratePlan"] = o.RatePlan
	}
	if true {
		toSerialize["unitGroup"] = o.UnitGroup
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.GuestComment != nil {
		toSerialize["guestComment"] = o.GuestComment
	}
	if true {
		toSerialize["cancellationFee"] = o.CancellationFee
	}
	if true {
		toSerialize["noShowFee"] = o.NoShowFee
	}
	if o.Company != nil {
		toSerialize["company"] = o.Company
	}
	return json.Marshal(toSerialize)
}

type NullableBookingReservationModel struct {
	value *BookingReservationModel
	isSet bool
}

func (v NullableBookingReservationModel) Get() *BookingReservationModel {
	return v.value
}

func (v *NullableBookingReservationModel) Set(val *BookingReservationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBookingReservationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBookingReservationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookingReservationModel(val *BookingReservationModel) *NullableBookingReservationModel {
	return &NullableBookingReservationModel{value: val, isSet: true}
}

func (v NullableBookingReservationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookingReservationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


