/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// ReservationNoShowFeeModel struct for ReservationNoShowFeeModel
type ReservationNoShowFeeModel struct {
	// The id of the no-show policy applied
	Id string `json:"id"`
	// The code of the no-show policy applied
	Code string `json:"code"`
	// The name of the no-show policy applied
	Name string `json:"name"`
	// The description of the no-show policy applied
	Description string `json:"description"`
	Fee MonetaryValueModel `json:"fee"`
}

// NewReservationNoShowFeeModel instantiates a new ReservationNoShowFeeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationNoShowFeeModel(id string, code string, name string, description string, fee MonetaryValueModel) *ReservationNoShowFeeModel {
	this := ReservationNoShowFeeModel{}
	this.Id = id
	this.Code = code
	this.Name = name
	this.Description = description
	this.Fee = fee
	return &this
}

// NewReservationNoShowFeeModelWithDefaults instantiates a new ReservationNoShowFeeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationNoShowFeeModelWithDefaults() *ReservationNoShowFeeModel {
	this := ReservationNoShowFeeModel{}
	return &this
}

// GetId returns the Id field value
func (o *ReservationNoShowFeeModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReservationNoShowFeeModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReservationNoShowFeeModel) SetId(v string) {
	o.Id = v
}

// GetCode returns the Code field value
func (o *ReservationNoShowFeeModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ReservationNoShowFeeModel) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ReservationNoShowFeeModel) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *ReservationNoShowFeeModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ReservationNoShowFeeModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ReservationNoShowFeeModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ReservationNoShowFeeModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ReservationNoShowFeeModel) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ReservationNoShowFeeModel) SetDescription(v string) {
	o.Description = v
}

// GetFee returns the Fee field value
func (o *ReservationNoShowFeeModel) GetFee() MonetaryValueModel {
	if o == nil {
		var ret MonetaryValueModel
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *ReservationNoShowFeeModel) GetFeeOk() (*MonetaryValueModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *ReservationNoShowFeeModel) SetFee(v MonetaryValueModel) {
	o.Fee = v
}

func (o ReservationNoShowFeeModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["fee"] = o.Fee
	}
	return json.Marshal(toSerialize)
}

type NullableReservationNoShowFeeModel struct {
	value *ReservationNoShowFeeModel
	isSet bool
}

func (v NullableReservationNoShowFeeModel) Get() *ReservationNoShowFeeModel {
	return v.value
}

func (v *NullableReservationNoShowFeeModel) Set(val *ReservationNoShowFeeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationNoShowFeeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationNoShowFeeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationNoShowFeeModel(val *ReservationNoShowFeeModel) *NullableReservationNoShowFeeModel {
	return &NullableReservationNoShowFeeModel{value: val, isSet: true}
}

func (v NullableReservationNoShowFeeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationNoShowFeeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


