/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
	"time"
)

// ReservationStayOfferTimeSliceModel struct for ReservationStayOfferTimeSliceModel
type ReservationStayOfferTimeSliceModel struct {
	// The start date and time for this time slice<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	From time.Time `json:"from"`
	// The end date and time for this time slice<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	To time.Time `json:"to"`
	RatePlan EmbeddedRatePlanModel `json:"ratePlan"`
	UnitGroup OfferUnitGroupModel `json:"unitGroup"`
	BaseAmount AmountModel `json:"baseAmount"`
	TotalGrossAmount MonetaryValueModel `json:"totalGrossAmount"`
	// The breakdown for services included in the offer
	IncludedServices *[]ReservationStayOfferServiceModel `json:"includedServices,omitempty"`
}

// NewReservationStayOfferTimeSliceModel instantiates a new ReservationStayOfferTimeSliceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationStayOfferTimeSliceModel(from time.Time, to time.Time, ratePlan EmbeddedRatePlanModel, unitGroup OfferUnitGroupModel, baseAmount AmountModel, totalGrossAmount MonetaryValueModel) *ReservationStayOfferTimeSliceModel {
	this := ReservationStayOfferTimeSliceModel{}
	this.From = from
	this.To = to
	this.RatePlan = ratePlan
	this.UnitGroup = unitGroup
	this.BaseAmount = baseAmount
	this.TotalGrossAmount = totalGrossAmount
	return &this
}

// NewReservationStayOfferTimeSliceModelWithDefaults instantiates a new ReservationStayOfferTimeSliceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationStayOfferTimeSliceModelWithDefaults() *ReservationStayOfferTimeSliceModel {
	this := ReservationStayOfferTimeSliceModel{}
	return &this
}

// GetFrom returns the From field value
func (o *ReservationStayOfferTimeSliceModel) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetFromOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *ReservationStayOfferTimeSliceModel) SetFrom(v time.Time) {
	o.From = v
}

// GetTo returns the To field value
func (o *ReservationStayOfferTimeSliceModel) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetToOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ReservationStayOfferTimeSliceModel) SetTo(v time.Time) {
	o.To = v
}

// GetRatePlan returns the RatePlan field value
func (o *ReservationStayOfferTimeSliceModel) GetRatePlan() EmbeddedRatePlanModel {
	if o == nil {
		var ret EmbeddedRatePlanModel
		return ret
	}

	return o.RatePlan
}

// GetRatePlanOk returns a tuple with the RatePlan field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetRatePlanOk() (*EmbeddedRatePlanModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RatePlan, true
}

// SetRatePlan sets field value
func (o *ReservationStayOfferTimeSliceModel) SetRatePlan(v EmbeddedRatePlanModel) {
	o.RatePlan = v
}

// GetUnitGroup returns the UnitGroup field value
func (o *ReservationStayOfferTimeSliceModel) GetUnitGroup() OfferUnitGroupModel {
	if o == nil {
		var ret OfferUnitGroupModel
		return ret
	}

	return o.UnitGroup
}

// GetUnitGroupOk returns a tuple with the UnitGroup field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetUnitGroupOk() (*OfferUnitGroupModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnitGroup, true
}

// SetUnitGroup sets field value
func (o *ReservationStayOfferTimeSliceModel) SetUnitGroup(v OfferUnitGroupModel) {
	o.UnitGroup = v
}

// GetBaseAmount returns the BaseAmount field value
func (o *ReservationStayOfferTimeSliceModel) GetBaseAmount() AmountModel {
	if o == nil {
		var ret AmountModel
		return ret
	}

	return o.BaseAmount
}

// GetBaseAmountOk returns a tuple with the BaseAmount field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetBaseAmountOk() (*AmountModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseAmount, true
}

// SetBaseAmount sets field value
func (o *ReservationStayOfferTimeSliceModel) SetBaseAmount(v AmountModel) {
	o.BaseAmount = v
}

// GetTotalGrossAmount returns the TotalGrossAmount field value
func (o *ReservationStayOfferTimeSliceModel) GetTotalGrossAmount() MonetaryValueModel {
	if o == nil {
		var ret MonetaryValueModel
		return ret
	}

	return o.TotalGrossAmount
}

// GetTotalGrossAmountOk returns a tuple with the TotalGrossAmount field value
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetTotalGrossAmountOk() (*MonetaryValueModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalGrossAmount, true
}

// SetTotalGrossAmount sets field value
func (o *ReservationStayOfferTimeSliceModel) SetTotalGrossAmount(v MonetaryValueModel) {
	o.TotalGrossAmount = v
}

// GetIncludedServices returns the IncludedServices field value if set, zero value otherwise.
func (o *ReservationStayOfferTimeSliceModel) GetIncludedServices() []ReservationStayOfferServiceModel {
	if o == nil || o.IncludedServices == nil {
		var ret []ReservationStayOfferServiceModel
		return ret
	}
	return *o.IncludedServices
}

// GetIncludedServicesOk returns a tuple with the IncludedServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReservationStayOfferTimeSliceModel) GetIncludedServicesOk() (*[]ReservationStayOfferServiceModel, bool) {
	if o == nil || o.IncludedServices == nil {
		return nil, false
	}
	return o.IncludedServices, true
}

// HasIncludedServices returns a boolean if a field has been set.
func (o *ReservationStayOfferTimeSliceModel) HasIncludedServices() bool {
	if o != nil && o.IncludedServices != nil {
		return true
	}

	return false
}

// SetIncludedServices gets a reference to the given []ReservationStayOfferServiceModel and assigns it to the IncludedServices field.
func (o *ReservationStayOfferTimeSliceModel) SetIncludedServices(v []ReservationStayOfferServiceModel) {
	o.IncludedServices = &v
}

func (o ReservationStayOfferTimeSliceModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["ratePlan"] = o.RatePlan
	}
	if true {
		toSerialize["unitGroup"] = o.UnitGroup
	}
	if true {
		toSerialize["baseAmount"] = o.BaseAmount
	}
	if true {
		toSerialize["totalGrossAmount"] = o.TotalGrossAmount
	}
	if o.IncludedServices != nil {
		toSerialize["includedServices"] = o.IncludedServices
	}
	return json.Marshal(toSerialize)
}

type NullableReservationStayOfferTimeSliceModel struct {
	value *ReservationStayOfferTimeSliceModel
	isSet bool
}

func (v NullableReservationStayOfferTimeSliceModel) Get() *ReservationStayOfferTimeSliceModel {
	return v.value
}

func (v *NullableReservationStayOfferTimeSliceModel) Set(val *ReservationStayOfferTimeSliceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationStayOfferTimeSliceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationStayOfferTimeSliceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationStayOfferTimeSliceModel(val *ReservationStayOfferTimeSliceModel) *NullableReservationStayOfferTimeSliceModel {
	return &NullableReservationStayOfferTimeSliceModel{value: val, isSet: true}
}

func (v NullableReservationStayOfferTimeSliceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationStayOfferTimeSliceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


