/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
)

// CreateReservationModel With this request you can create a reservation
type CreateReservationModel struct {
	// Date and optional time of arrival<br />Specify either a pure date or a date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Arrival string `json:"arrival"`
	// Date and optional time of departure. Cannot be more than 5 years after arrival.<br />Specify either a pure date or a date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Departure string `json:"departure"`
	// Number of adults
	Adults int32 `json:"adults"`
	// Ages of the children
	ChildrenAges *[]int32 `json:"childrenAges,omitempty"`
	// Additional information and comments
	Comment *string `json:"comment,omitempty"`
	// Additional information and comments by the guest
	GuestComment *string `json:"guestComment,omitempty"`
	// Code in some system
	ExternalCode *string `json:"externalCode,omitempty"`
	// Channel code
	ChannelCode string `json:"channelCode"`
	// Source of the reservation
	Source *string `json:"source,omitempty"`
	PrimaryGuest *GuestModel `json:"primaryGuest,omitempty"`
	// Additional guests of the reservation.
	AdditionalGuests *[]GuestModel `json:"additionalGuests,omitempty"`
	// The guarantee that has to be applied for this reservation. It has to be the same or stronger than  the minimum guarantee required by the selected rate plan
	GuaranteeType *string `json:"guaranteeType,omitempty"`
	// Purpose of the trip, leisure or business
	TravelPurpose *string `json:"travelPurpose,omitempty"`
	// Gross prices including services and taxes for each time slice. They will be applied to the reservation timeslices  in the order specified from arrival to departure
	TimeSlices []CreateReservationTimeSliceModel `json:"timeSlices"`
	// Additional services (extras, add-ons) that should be added to the reservation
	Services *[]BookReservationServiceModel `json:"services,omitempty"`
	// Set this if this reservation belongs to a company
	CompanyId *string `json:"companyId,omitempty"`
	// Corporate code provided during creation. Used to find offers during amend.
	CorporateCode *string `json:"corporateCode,omitempty"`
	PrePaymentAmount *MonetaryValueModel `json:"prePaymentAmount,omitempty"`
	Commission *CommissionModel `json:"commission,omitempty"`
	// The promo code associated with a certain special offer
	PromoCode *string `json:"promoCode,omitempty"`
}

// NewCreateReservationModel instantiates a new CreateReservationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateReservationModel(arrival string, departure string, adults int32, channelCode string, timeSlices []CreateReservationTimeSliceModel) *CreateReservationModel {
	this := CreateReservationModel{}
	this.Arrival = arrival
	this.Departure = departure
	this.Adults = adults
	this.ChannelCode = channelCode
	this.TimeSlices = timeSlices
	return &this
}

// NewCreateReservationModelWithDefaults instantiates a new CreateReservationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateReservationModelWithDefaults() *CreateReservationModel {
	this := CreateReservationModel{}
	return &this
}

// GetArrival returns the Arrival field value
func (o *CreateReservationModel) GetArrival() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Arrival
}

// GetArrivalOk returns a tuple with the Arrival field value
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetArrivalOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Arrival, true
}

// SetArrival sets field value
func (o *CreateReservationModel) SetArrival(v string) {
	o.Arrival = v
}

// GetDeparture returns the Departure field value
func (o *CreateReservationModel) GetDeparture() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Departure
}

// GetDepartureOk returns a tuple with the Departure field value
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetDepartureOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Departure, true
}

// SetDeparture sets field value
func (o *CreateReservationModel) SetDeparture(v string) {
	o.Departure = v
}

// GetAdults returns the Adults field value
func (o *CreateReservationModel) GetAdults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Adults
}

// GetAdultsOk returns a tuple with the Adults field value
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetAdultsOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Adults, true
}

// SetAdults sets field value
func (o *CreateReservationModel) SetAdults(v int32) {
	o.Adults = v
}

// GetChildrenAges returns the ChildrenAges field value if set, zero value otherwise.
func (o *CreateReservationModel) GetChildrenAges() []int32 {
	if o == nil || o.ChildrenAges == nil {
		var ret []int32
		return ret
	}
	return *o.ChildrenAges
}

// GetChildrenAgesOk returns a tuple with the ChildrenAges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetChildrenAgesOk() (*[]int32, bool) {
	if o == nil || o.ChildrenAges == nil {
		return nil, false
	}
	return o.ChildrenAges, true
}

// HasChildrenAges returns a boolean if a field has been set.
func (o *CreateReservationModel) HasChildrenAges() bool {
	if o != nil && o.ChildrenAges != nil {
		return true
	}

	return false
}

// SetChildrenAges gets a reference to the given []int32 and assigns it to the ChildrenAges field.
func (o *CreateReservationModel) SetChildrenAges(v []int32) {
	o.ChildrenAges = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *CreateReservationModel) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *CreateReservationModel) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *CreateReservationModel) SetComment(v string) {
	o.Comment = &v
}

// GetGuestComment returns the GuestComment field value if set, zero value otherwise.
func (o *CreateReservationModel) GetGuestComment() string {
	if o == nil || o.GuestComment == nil {
		var ret string
		return ret
	}
	return *o.GuestComment
}

// GetGuestCommentOk returns a tuple with the GuestComment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetGuestCommentOk() (*string, bool) {
	if o == nil || o.GuestComment == nil {
		return nil, false
	}
	return o.GuestComment, true
}

// HasGuestComment returns a boolean if a field has been set.
func (o *CreateReservationModel) HasGuestComment() bool {
	if o != nil && o.GuestComment != nil {
		return true
	}

	return false
}

// SetGuestComment gets a reference to the given string and assigns it to the GuestComment field.
func (o *CreateReservationModel) SetGuestComment(v string) {
	o.GuestComment = &v
}

// GetExternalCode returns the ExternalCode field value if set, zero value otherwise.
func (o *CreateReservationModel) GetExternalCode() string {
	if o == nil || o.ExternalCode == nil {
		var ret string
		return ret
	}
	return *o.ExternalCode
}

// GetExternalCodeOk returns a tuple with the ExternalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetExternalCodeOk() (*string, bool) {
	if o == nil || o.ExternalCode == nil {
		return nil, false
	}
	return o.ExternalCode, true
}

// HasExternalCode returns a boolean if a field has been set.
func (o *CreateReservationModel) HasExternalCode() bool {
	if o != nil && o.ExternalCode != nil {
		return true
	}

	return false
}

// SetExternalCode gets a reference to the given string and assigns it to the ExternalCode field.
func (o *CreateReservationModel) SetExternalCode(v string) {
	o.ExternalCode = &v
}

// GetChannelCode returns the ChannelCode field value
func (o *CreateReservationModel) GetChannelCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetChannelCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *CreateReservationModel) SetChannelCode(v string) {
	o.ChannelCode = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CreateReservationModel) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CreateReservationModel) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *CreateReservationModel) SetSource(v string) {
	o.Source = &v
}

// GetPrimaryGuest returns the PrimaryGuest field value if set, zero value otherwise.
func (o *CreateReservationModel) GetPrimaryGuest() GuestModel {
	if o == nil || o.PrimaryGuest == nil {
		var ret GuestModel
		return ret
	}
	return *o.PrimaryGuest
}

// GetPrimaryGuestOk returns a tuple with the PrimaryGuest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetPrimaryGuestOk() (*GuestModel, bool) {
	if o == nil || o.PrimaryGuest == nil {
		return nil, false
	}
	return o.PrimaryGuest, true
}

// HasPrimaryGuest returns a boolean if a field has been set.
func (o *CreateReservationModel) HasPrimaryGuest() bool {
	if o != nil && o.PrimaryGuest != nil {
		return true
	}

	return false
}

// SetPrimaryGuest gets a reference to the given GuestModel and assigns it to the PrimaryGuest field.
func (o *CreateReservationModel) SetPrimaryGuest(v GuestModel) {
	o.PrimaryGuest = &v
}

// GetAdditionalGuests returns the AdditionalGuests field value if set, zero value otherwise.
func (o *CreateReservationModel) GetAdditionalGuests() []GuestModel {
	if o == nil || o.AdditionalGuests == nil {
		var ret []GuestModel
		return ret
	}
	return *o.AdditionalGuests
}

// GetAdditionalGuestsOk returns a tuple with the AdditionalGuests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetAdditionalGuestsOk() (*[]GuestModel, bool) {
	if o == nil || o.AdditionalGuests == nil {
		return nil, false
	}
	return o.AdditionalGuests, true
}

// HasAdditionalGuests returns a boolean if a field has been set.
func (o *CreateReservationModel) HasAdditionalGuests() bool {
	if o != nil && o.AdditionalGuests != nil {
		return true
	}

	return false
}

// SetAdditionalGuests gets a reference to the given []GuestModel and assigns it to the AdditionalGuests field.
func (o *CreateReservationModel) SetAdditionalGuests(v []GuestModel) {
	o.AdditionalGuests = &v
}

// GetGuaranteeType returns the GuaranteeType field value if set, zero value otherwise.
func (o *CreateReservationModel) GetGuaranteeType() string {
	if o == nil || o.GuaranteeType == nil {
		var ret string
		return ret
	}
	return *o.GuaranteeType
}

// GetGuaranteeTypeOk returns a tuple with the GuaranteeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetGuaranteeTypeOk() (*string, bool) {
	if o == nil || o.GuaranteeType == nil {
		return nil, false
	}
	return o.GuaranteeType, true
}

// HasGuaranteeType returns a boolean if a field has been set.
func (o *CreateReservationModel) HasGuaranteeType() bool {
	if o != nil && o.GuaranteeType != nil {
		return true
	}

	return false
}

// SetGuaranteeType gets a reference to the given string and assigns it to the GuaranteeType field.
func (o *CreateReservationModel) SetGuaranteeType(v string) {
	o.GuaranteeType = &v
}

// GetTravelPurpose returns the TravelPurpose field value if set, zero value otherwise.
func (o *CreateReservationModel) GetTravelPurpose() string {
	if o == nil || o.TravelPurpose == nil {
		var ret string
		return ret
	}
	return *o.TravelPurpose
}

// GetTravelPurposeOk returns a tuple with the TravelPurpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetTravelPurposeOk() (*string, bool) {
	if o == nil || o.TravelPurpose == nil {
		return nil, false
	}
	return o.TravelPurpose, true
}

// HasTravelPurpose returns a boolean if a field has been set.
func (o *CreateReservationModel) HasTravelPurpose() bool {
	if o != nil && o.TravelPurpose != nil {
		return true
	}

	return false
}

// SetTravelPurpose gets a reference to the given string and assigns it to the TravelPurpose field.
func (o *CreateReservationModel) SetTravelPurpose(v string) {
	o.TravelPurpose = &v
}

// GetTimeSlices returns the TimeSlices field value
func (o *CreateReservationModel) GetTimeSlices() []CreateReservationTimeSliceModel {
	if o == nil {
		var ret []CreateReservationTimeSliceModel
		return ret
	}

	return o.TimeSlices
}

// GetTimeSlicesOk returns a tuple with the TimeSlices field value
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetTimeSlicesOk() (*[]CreateReservationTimeSliceModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TimeSlices, true
}

// SetTimeSlices sets field value
func (o *CreateReservationModel) SetTimeSlices(v []CreateReservationTimeSliceModel) {
	o.TimeSlices = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *CreateReservationModel) GetServices() []BookReservationServiceModel {
	if o == nil || o.Services == nil {
		var ret []BookReservationServiceModel
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetServicesOk() (*[]BookReservationServiceModel, bool) {
	if o == nil || o.Services == nil {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *CreateReservationModel) HasServices() bool {
	if o != nil && o.Services != nil {
		return true
	}

	return false
}

// SetServices gets a reference to the given []BookReservationServiceModel and assigns it to the Services field.
func (o *CreateReservationModel) SetServices(v []BookReservationServiceModel) {
	o.Services = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *CreateReservationModel) GetCompanyId() string {
	if o == nil || o.CompanyId == nil {
		var ret string
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetCompanyIdOk() (*string, bool) {
	if o == nil || o.CompanyId == nil {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *CreateReservationModel) HasCompanyId() bool {
	if o != nil && o.CompanyId != nil {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given string and assigns it to the CompanyId field.
func (o *CreateReservationModel) SetCompanyId(v string) {
	o.CompanyId = &v
}

// GetCorporateCode returns the CorporateCode field value if set, zero value otherwise.
func (o *CreateReservationModel) GetCorporateCode() string {
	if o == nil || o.CorporateCode == nil {
		var ret string
		return ret
	}
	return *o.CorporateCode
}

// GetCorporateCodeOk returns a tuple with the CorporateCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetCorporateCodeOk() (*string, bool) {
	if o == nil || o.CorporateCode == nil {
		return nil, false
	}
	return o.CorporateCode, true
}

// HasCorporateCode returns a boolean if a field has been set.
func (o *CreateReservationModel) HasCorporateCode() bool {
	if o != nil && o.CorporateCode != nil {
		return true
	}

	return false
}

// SetCorporateCode gets a reference to the given string and assigns it to the CorporateCode field.
func (o *CreateReservationModel) SetCorporateCode(v string) {
	o.CorporateCode = &v
}

// GetPrePaymentAmount returns the PrePaymentAmount field value if set, zero value otherwise.
func (o *CreateReservationModel) GetPrePaymentAmount() MonetaryValueModel {
	if o == nil || o.PrePaymentAmount == nil {
		var ret MonetaryValueModel
		return ret
	}
	return *o.PrePaymentAmount
}

// GetPrePaymentAmountOk returns a tuple with the PrePaymentAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetPrePaymentAmountOk() (*MonetaryValueModel, bool) {
	if o == nil || o.PrePaymentAmount == nil {
		return nil, false
	}
	return o.PrePaymentAmount, true
}

// HasPrePaymentAmount returns a boolean if a field has been set.
func (o *CreateReservationModel) HasPrePaymentAmount() bool {
	if o != nil && o.PrePaymentAmount != nil {
		return true
	}

	return false
}

// SetPrePaymentAmount gets a reference to the given MonetaryValueModel and assigns it to the PrePaymentAmount field.
func (o *CreateReservationModel) SetPrePaymentAmount(v MonetaryValueModel) {
	o.PrePaymentAmount = &v
}

// GetCommission returns the Commission field value if set, zero value otherwise.
func (o *CreateReservationModel) GetCommission() CommissionModel {
	if o == nil || o.Commission == nil {
		var ret CommissionModel
		return ret
	}
	return *o.Commission
}

// GetCommissionOk returns a tuple with the Commission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetCommissionOk() (*CommissionModel, bool) {
	if o == nil || o.Commission == nil {
		return nil, false
	}
	return o.Commission, true
}

// HasCommission returns a boolean if a field has been set.
func (o *CreateReservationModel) HasCommission() bool {
	if o != nil && o.Commission != nil {
		return true
	}

	return false
}

// SetCommission gets a reference to the given CommissionModel and assigns it to the Commission field.
func (o *CreateReservationModel) SetCommission(v CommissionModel) {
	o.Commission = &v
}

// GetPromoCode returns the PromoCode field value if set, zero value otherwise.
func (o *CreateReservationModel) GetPromoCode() string {
	if o == nil || o.PromoCode == nil {
		var ret string
		return ret
	}
	return *o.PromoCode
}

// GetPromoCodeOk returns a tuple with the PromoCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReservationModel) GetPromoCodeOk() (*string, bool) {
	if o == nil || o.PromoCode == nil {
		return nil, false
	}
	return o.PromoCode, true
}

// HasPromoCode returns a boolean if a field has been set.
func (o *CreateReservationModel) HasPromoCode() bool {
	if o != nil && o.PromoCode != nil {
		return true
	}

	return false
}

// SetPromoCode gets a reference to the given string and assigns it to the PromoCode field.
func (o *CreateReservationModel) SetPromoCode(v string) {
	o.PromoCode = &v
}

func (o CreateReservationModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["arrival"] = o.Arrival
	}
	if true {
		toSerialize["departure"] = o.Departure
	}
	if true {
		toSerialize["adults"] = o.Adults
	}
	if o.ChildrenAges != nil {
		toSerialize["childrenAges"] = o.ChildrenAges
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.GuestComment != nil {
		toSerialize["guestComment"] = o.GuestComment
	}
	if o.ExternalCode != nil {
		toSerialize["externalCode"] = o.ExternalCode
	}
	if true {
		toSerialize["channelCode"] = o.ChannelCode
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.PrimaryGuest != nil {
		toSerialize["primaryGuest"] = o.PrimaryGuest
	}
	if o.AdditionalGuests != nil {
		toSerialize["additionalGuests"] = o.AdditionalGuests
	}
	if o.GuaranteeType != nil {
		toSerialize["guaranteeType"] = o.GuaranteeType
	}
	if o.TravelPurpose != nil {
		toSerialize["travelPurpose"] = o.TravelPurpose
	}
	if true {
		toSerialize["timeSlices"] = o.TimeSlices
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.CompanyId != nil {
		toSerialize["companyId"] = o.CompanyId
	}
	if o.CorporateCode != nil {
		toSerialize["corporateCode"] = o.CorporateCode
	}
	if o.PrePaymentAmount != nil {
		toSerialize["prePaymentAmount"] = o.PrePaymentAmount
	}
	if o.Commission != nil {
		toSerialize["commission"] = o.Commission
	}
	if o.PromoCode != nil {
		toSerialize["promoCode"] = o.PromoCode
	}
	return json.Marshal(toSerialize)
}

type NullableCreateReservationModel struct {
	value *CreateReservationModel
	isSet bool
}

func (v NullableCreateReservationModel) Get() *CreateReservationModel {
	return v.value
}

func (v *NullableCreateReservationModel) Set(val *CreateReservationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateReservationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateReservationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateReservationModel(val *CreateReservationModel) *NullableCreateReservationModel {
	return &NullableCreateReservationModel{value: val, isSet: true}
}

func (v NullableCreateReservationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateReservationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


