/*
 * apaleo Booking API
 *
 * Resources and methods to manage guest journeys.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bookingclient

import (
	"encoding/json"
	"time"
)

// GroupItemModel struct for GroupItemModel
type GroupItemModel struct {
	// Group id
	Id string `json:"id"`
	// Start date and time of the earliest block for this group<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	From *time.Time `json:"from,omitempty"`
	// End date and time of the latest block for this group<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	To *time.Time `json:"to,omitempty"`
	// Name of the group
	Name string `json:"name"`
	Booker *BookerModel `json:"booker,omitempty"`
	// Additional information and comments
	Comment *string `json:"comment,omitempty"`
	// Additional information and comment by the booker
	BookerComment *string `json:"bookerComment,omitempty"`
	PaymentAccount *PaymentAccountModel `json:"paymentAccount,omitempty"`
	// Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Created time.Time `json:"created"`
	// Date of last modification<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
	Modified time.Time `json:"modified"`
	// Blocks within this group
	Blocks *[]GroupBlockModel `json:"blocks,omitempty"`
	// The list of actions for this group
	Actions *[]ActionModelGroupActionNotAllowedGroupActionReason `json:"actions,omitempty"`
	// The list of property ids this group belongs to
	PropertyIds []string `json:"propertyIds"`
}

// NewGroupItemModel instantiates a new GroupItemModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupItemModel(id string, name string, created time.Time, modified time.Time, propertyIds []string) *GroupItemModel {
	this := GroupItemModel{}
	this.Id = id
	this.Name = name
	this.Created = created
	this.Modified = modified
	this.PropertyIds = propertyIds
	return &this
}

// NewGroupItemModelWithDefaults instantiates a new GroupItemModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupItemModelWithDefaults() *GroupItemModel {
	this := GroupItemModel{}
	return &this
}

// GetId returns the Id field value
func (o *GroupItemModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupItemModel) SetId(v string) {
	o.Id = v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *GroupItemModel) GetFrom() time.Time {
	if o == nil || o.From == nil {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetFromOk() (*time.Time, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *GroupItemModel) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *GroupItemModel) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *GroupItemModel) GetTo() time.Time {
	if o == nil || o.To == nil {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetToOk() (*time.Time, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *GroupItemModel) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *GroupItemModel) SetTo(v time.Time) {
	o.To = &v
}

// GetName returns the Name field value
func (o *GroupItemModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupItemModel) SetName(v string) {
	o.Name = v
}

// GetBooker returns the Booker field value if set, zero value otherwise.
func (o *GroupItemModel) GetBooker() BookerModel {
	if o == nil || o.Booker == nil {
		var ret BookerModel
		return ret
	}
	return *o.Booker
}

// GetBookerOk returns a tuple with the Booker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetBookerOk() (*BookerModel, bool) {
	if o == nil || o.Booker == nil {
		return nil, false
	}
	return o.Booker, true
}

// HasBooker returns a boolean if a field has been set.
func (o *GroupItemModel) HasBooker() bool {
	if o != nil && o.Booker != nil {
		return true
	}

	return false
}

// SetBooker gets a reference to the given BookerModel and assigns it to the Booker field.
func (o *GroupItemModel) SetBooker(v BookerModel) {
	o.Booker = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *GroupItemModel) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *GroupItemModel) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *GroupItemModel) SetComment(v string) {
	o.Comment = &v
}

// GetBookerComment returns the BookerComment field value if set, zero value otherwise.
func (o *GroupItemModel) GetBookerComment() string {
	if o == nil || o.BookerComment == nil {
		var ret string
		return ret
	}
	return *o.BookerComment
}

// GetBookerCommentOk returns a tuple with the BookerComment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetBookerCommentOk() (*string, bool) {
	if o == nil || o.BookerComment == nil {
		return nil, false
	}
	return o.BookerComment, true
}

// HasBookerComment returns a boolean if a field has been set.
func (o *GroupItemModel) HasBookerComment() bool {
	if o != nil && o.BookerComment != nil {
		return true
	}

	return false
}

// SetBookerComment gets a reference to the given string and assigns it to the BookerComment field.
func (o *GroupItemModel) SetBookerComment(v string) {
	o.BookerComment = &v
}

// GetPaymentAccount returns the PaymentAccount field value if set, zero value otherwise.
func (o *GroupItemModel) GetPaymentAccount() PaymentAccountModel {
	if o == nil || o.PaymentAccount == nil {
		var ret PaymentAccountModel
		return ret
	}
	return *o.PaymentAccount
}

// GetPaymentAccountOk returns a tuple with the PaymentAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetPaymentAccountOk() (*PaymentAccountModel, bool) {
	if o == nil || o.PaymentAccount == nil {
		return nil, false
	}
	return o.PaymentAccount, true
}

// HasPaymentAccount returns a boolean if a field has been set.
func (o *GroupItemModel) HasPaymentAccount() bool {
	if o != nil && o.PaymentAccount != nil {
		return true
	}

	return false
}

// SetPaymentAccount gets a reference to the given PaymentAccountModel and assigns it to the PaymentAccount field.
func (o *GroupItemModel) SetPaymentAccount(v PaymentAccountModel) {
	o.PaymentAccount = &v
}

// GetCreated returns the Created field value
func (o *GroupItemModel) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetCreatedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *GroupItemModel) SetCreated(v time.Time) {
	o.Created = v
}

// GetModified returns the Modified field value
func (o *GroupItemModel) GetModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetModifiedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Modified, true
}

// SetModified sets field value
func (o *GroupItemModel) SetModified(v time.Time) {
	o.Modified = v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *GroupItemModel) GetBlocks() []GroupBlockModel {
	if o == nil || o.Blocks == nil {
		var ret []GroupBlockModel
		return ret
	}
	return *o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetBlocksOk() (*[]GroupBlockModel, bool) {
	if o == nil || o.Blocks == nil {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *GroupItemModel) HasBlocks() bool {
	if o != nil && o.Blocks != nil {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []GroupBlockModel and assigns it to the Blocks field.
func (o *GroupItemModel) SetBlocks(v []GroupBlockModel) {
	o.Blocks = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *GroupItemModel) GetActions() []ActionModelGroupActionNotAllowedGroupActionReason {
	if o == nil || o.Actions == nil {
		var ret []ActionModelGroupActionNotAllowedGroupActionReason
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetActionsOk() (*[]ActionModelGroupActionNotAllowedGroupActionReason, bool) {
	if o == nil || o.Actions == nil {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *GroupItemModel) HasActions() bool {
	if o != nil && o.Actions != nil {
		return true
	}

	return false
}

// SetActions gets a reference to the given []ActionModelGroupActionNotAllowedGroupActionReason and assigns it to the Actions field.
func (o *GroupItemModel) SetActions(v []ActionModelGroupActionNotAllowedGroupActionReason) {
	o.Actions = &v
}

// GetPropertyIds returns the PropertyIds field value
func (o *GroupItemModel) GetPropertyIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PropertyIds
}

// GetPropertyIdsOk returns a tuple with the PropertyIds field value
// and a boolean to check if the value has been set.
func (o *GroupItemModel) GetPropertyIdsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PropertyIds, true
}

// SetPropertyIds sets field value
func (o *GroupItemModel) SetPropertyIds(v []string) {
	o.PropertyIds = v
}

func (o GroupItemModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.From != nil {
		toSerialize["from"] = o.From
	}
	if o.To != nil {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Booker != nil {
		toSerialize["booker"] = o.Booker
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.BookerComment != nil {
		toSerialize["bookerComment"] = o.BookerComment
	}
	if o.PaymentAccount != nil {
		toSerialize["paymentAccount"] = o.PaymentAccount
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["modified"] = o.Modified
	}
	if o.Blocks != nil {
		toSerialize["blocks"] = o.Blocks
	}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	if true {
		toSerialize["propertyIds"] = o.PropertyIds
	}
	return json.Marshal(toSerialize)
}

type NullableGroupItemModel struct {
	value *GroupItemModel
	isSet bool
}

func (v NullableGroupItemModel) Get() *GroupItemModel {
	return v.value
}

func (v *NullableGroupItemModel) Set(val *GroupItemModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupItemModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupItemModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupItemModel(val *GroupItemModel) *NullableGroupItemModel {
	return &NullableGroupItemModel{value: val, isSet: true}
}

func (v NullableGroupItemModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupItemModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


