// Code generated by qtc from "500.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line 500.qtpl:1
package templates

//line 500.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line 500.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line 500.qtpl:2
type ErrorPage struct {
	BasePage
}

//line 500.qtpl:7
func (p *ErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
//line 500.qtpl:7
	qw422016.N().S(`
	Something went wrong
`)
//line 500.qtpl:9
}

//line 500.qtpl:9
func (p *ErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
//line 500.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line 500.qtpl:9
	p.StreamTitle(qw422016)
//line 500.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line 500.qtpl:9
}

//line 500.qtpl:9
func (p *ErrorPage) Title() string {
//line 500.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line 500.qtpl:9
	p.WriteTitle(qb422016)
//line 500.qtpl:9
	qs422016 := string(qb422016.B)
//line 500.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line 500.qtpl:9
	return qs422016
//line 500.qtpl:9
}

//line 500.qtpl:11
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line 500.qtpl:11
	qw422016.N().S(`
	<h1>Error page</h1>
	<h3>
		Ooops... something went wrong. We are looking into it.
	</h3>
`)
//line 500.qtpl:16
}

//line 500.qtpl:16
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line 500.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line 500.qtpl:16
	p.StreamBody(qw422016)
//line 500.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line 500.qtpl:16
}

//line 500.qtpl:16
func (p *ErrorPage) Body() string {
//line 500.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line 500.qtpl:16
	p.WriteBody(qb422016)
//line 500.qtpl:16
	qs422016 := string(qb422016.B)
//line 500.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line 500.qtpl:16
	return qs422016
//line 500.qtpl:16
}
